### PR TITLE
Linux Agent: Streamline locale handling

### PR DESCRIPTION
**Pull request by rawiriblundell**
This PR simplifies and streamlines the locale handling at the start of the agent, making the search among the three preferred locales more portable and very slightly more performant.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Rawiri,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4338

**Comment by rawiriblundell** [comment]
Hi there,
another simple change to merge please.  This one gets rid of a shell loop, two unnecessary variable assignments, a call to the untrustworthy (and villainous :) ) echo, and a call to a non-portable use of grep.  It replaces all that with POSIX spec'd usage of locale, paste and a shell case statement.

A style note:  Balanced parentheses in case statements is POSIX compatible and helps with editors that do colour formatting and navigation based on bracket pairs e.g. vim.  Plus, subjectively, it looks cleaner IMHO.  See:

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/locale.html
https://pubs.opengroup.org/onlinepubs/009696699/utilities/paste.html
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04

Cheers!

**Comment by LarsMichelsen** [comment]
Again, thank you for your work. The change looks helpful.

We were apparently just at the same site. We have identified a number of new issues in the Linux agent for which I have just flagged 3 commits. The changes address slightly different things than your change. Please have a look at the commits and maybe rebase your change on top of it, so we can adopt it as well, if it still makes sense to you.

I noticed two more changes in your commit:

a) The code does not care about "C.utf8" anymore.
b) It now always sets LC_ALL. This was not the case before. Whether this is good or bad, I can't judge right now. I only see the difference.

**Comment by rawiriblundell** [comment]
Hmm.  I've tried to rebase and reset a few times to no avail.  Looks like someone with write access will have to review this.

In the latest changes, I move PATH right to the top as that's the most fundamental of env vars.  I move inpath() up a little and correct the command -v creep.  I've added "C.utf-8".  I'm not exactly sure why that disappeared, possibly a typo on my part.  Hard to tell as it was several months ago ;)

LC_ALL fails back to C, because in all the other *nix agent scripts, LC_ALL is simply set to C.  In other words: this is a small step towards merging the various *nix agent scripts.

**Comment by LarsMichelsen** [comment]
I pushed your change with some additional changes (bc739540671a73f718ebbfe47223896d950f19d0):

- Updated the commit message
- Added another inpath for the paste command
- Reduced the cases to C.UTF-8 and C.utf8. The previously explicitly handled C is now handled by the default value of LC_ALL.

Please have a look at it and let me know in case you have any comments.

**Comment by rawiriblundell** [comment]
Looks reasonable to me, let's close this PR and move on to the next one :)

**Pull request closed without merging**
