### PR TITLE
Etherbox: Skip not connected Sensors

### PR DESCRIPTION
**Pull request by Bastian-Kuhn**

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Bastian,

thank you for this fix. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-2925

**Comment by jonaskluger** [comment]
What type of sensor does the ID 3 ignore?

**Comment by Bastian-Kuhn** [comment]
Hi, it's more than a month ago. Don't know any more,
think it was humidity.

**Comment by jonaskluger** [comment]
Thank you Bastian.

The PR got resolved with the Werk 10082.
https://checkmk.com/check_mk-werks.php?werk_id=10082

**Pull request closed without merging**
