### PR TITLE
mk_redis: Support connecting via unix socket

### PR DESCRIPTION
**Pull request by moschlar**

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hey Moritz,
thanks for your pull request.
we removed the Python 2 support from our code base.
https://checkmk.com/check_mk-werks.php?werk_id=11080

Could you please rebase your code to the latest state of the master branch?
This should fix the failing python2 test.

Thanks a lot!
Best
Jonas

**Comment by jherbel** [comment]
Hello Moritz,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4600

**Comment by moschlar** [comment]
Thanks @jherbel - that would be great.
(Just to explain: My use case is a GitLab Omnibus installation that configures most services to just use unix sockets by default)

**Comment by mo-ki** [comment]
It appears that sockets are now supported in the plugin.
I'm sorry that we didn't manage to consider your contribution earlier.
It is much appreciated nevertheless!

**Pull request closed without merging**
