### PR TITLE
ports check_humidity to check API 2.0

### PR DESCRIPTION
**Pull request by gurubert**
from cmk/base/check_legacy_includes/humidity.py

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, thank you for this PR. What is the purpose of porting this function? Do you want to user it later on to port check plugins?

**Comment by gurubert** [comment]
Yes, I need it for humidity sensors in an SNMP plugin.

The function was available in the old check API and is still in check_legacy_includes but cannot be used with the 2.0 check API.
Other functions have been ported, e.g. check_temperature. This one seems to have been missed.

**Review by jherbel — CHANGES_REQUESTED** [review]
There is no need to handle all the different legacy parameter formats here. You can assume that this function is always handed the latest parameter format according to cmk/gui/plugins/wato/check_parameters/humidity.py. So you can simply use
`params: Mapping[str, Tuple[float, float]]`
and directly hand over the levels to `check_levels`:
`levels_upper=params.get("levels", (None, None))`

**Review by jherbel — APPROVED** [review]
Looks good now, I will merge this once we have another approved PR where this is used.

**Review by jherbel — APPROVED** [review]
Looks good, as I said, I will merge this once there is actual code using this function (s.t. we do not have unused code lying around).
You can simply commit the actual check plugin code in this PR as well. However, please try to keep it small, since we are currently not accepting new feature PRs (I would make a bit of an exception here).

**Comment by jherbel** [comment]
Closed this due to inactivity

**Pull request closed without merging**
