### PR TITLE
mssql_backup: ignore backup types for SIMPLE databases

### PR DESCRIPTION
**Pull request by gurubert**
This patch makes both mssql_backup checks ignore backups of the type "log" and "database diff" if the database is of recovery type SIMPLE.

These databases do not have transaction logs.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Robert,

thank you for this request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3200

**Comment by jonaskluger** [comment]
Hello Robert,

please make sure the test run without any errors. Looks like some tests are failing.


We also wanted to give you a heads up that we will start closing stale & inactive pull request from the end of the week.

Pull request that are pending because more information from the original contributor are needed or pull request that do not follow our contribution guidelines will be affected.

These pull request will be closed after 14 days of inactivity.

This will help us staying up to date with the suggested improvements from the community.
We really appreciate your contribution to our code base! Thank you a lot from the team!

All the best
Jonas

**Comment by gurubert** [comment]
Hi @jonaskluger and @LarsMichelsen,

I am trying to fulfill all the requirements, but I am just a consultant that is writing Python code, not a software developer that is fluent in Jenkins and unit tests.

Could you please support your external contributors that try to add value to the product?

I find it a little bit disappointing and excluding if you have the policy to close pull requests that do not pass all your tests without helping the contributors first. Is this how an open source development community should work?

When I first submitted the PR it passed the tests but then the tests changed. Why? How? I do not know. From my point of view I have to try and reverse engineer the unit tests as I do not know where to start looking for documentation.

This PR is now 5 months old…

**Comment by svenpanne** [comment]
> I am trying to fulfill all the requirements, but I am just a consultant that is writing Python code, not a software developer that is fluent in Jenkins and unit tests.

Well, you don't need to be "fluent in Jenkins", but writing and fixing unit tests with a standard unit test framework isn't that hard. Nevertheless, if you've got a concrete question about this, feel free to ask.

> Could you please support your external contributors that try to add value to the product?

I think we are already doing that: You can just submit your PRs, get automatic feedback resulting from various tests, etc.  What else are you expecting exactly? We can surely improve various things, but we need to know what.

> I find it a little bit disappointing and excluding if you have the policy to close pull requests that do not pass all your tests without helping the contributors first. Is this how an open source development community should work?

Please note that tons of Open Source projects out there don't even take the slightest look at PRs which don't pass CI tests. This _is_ how Open Source works, because that is more or less the only policy that scales. If you have problems fixing a test, you can explicitly ask for help, but you can't expect other people to just fix your bugs automagically.

> When I first submitted the PR it passed the tests but then the tests changed. Why? How? I do not know. From my point of view I have to try and reverse engineer the unit tests as I do not know where to start looking for documentation.

We are currently converting our code base to Python 3 plus we are introducing a new check API. Furthermore, we improved testing in various ways (added more mypy coverage etc.), so an older PR can fail now, even if it didn't fail before. So to get this PR into our code base, you have to rebase it and fix the resulting breakage. Note that e.g. the paths to the check unit tests has changed.

> This PR is now 5 months old…

That's because of man-power reasons, but we are hopefully improving here, too.

**Comment by gurubert** [comment]
Hi @svenpanne 

> > I am trying to fulfill all the requirements, but I am just a consultant that is writing Python code, not a software developer that is fluent in Jenkins and unit tests.
> 
> Well, you don't need to be "fluent in Jenkins", but writing and fixing unit tests with a standard unit test framework isn't that hard. Nevertheless, if you've got a concrete question about this, feel free to ask.

How do I fix the current build failure?

The pull requests introduces an additional "extra_section" to the check which should result in parsed[0] (original data) and parsed[1] (extra data). I tried to add the extra data to the unit test but this does not seem to work any more.

What "standard unit test framework" do you recommend to develop check**mk** checks?

**Comment by svenpanne** [comment]
The first step is to move the generic check test to the right directory (below `tests-py3/`, not `tests/` anymore). This is what https://travis-ci.com/github/tribe29/checkmk/jobs/319076988#L4012 is trying to tell you. Then let's see what happens...

Background: Currently we have a mix of Python 2 stuff and Python 3 code, so there are two test directories corresponding to that. As I said, we are in the middle of the Python 3 migration, and we hope to nuke Python 2 "soon". :grin:

**Comment by gurubert** [comment]
I now get the following error from the unit test:

        def assertBasicCheckResultsEqual(actual, expected):
            """
            Compare two BasicCheckResults.
        
            This gives more helpful output than 'assert actual == expected'
            """
            assert isinstance(actual, BasicCheckResult), "not a BasicCheckResult: %r" % actual
            assert isinstance(expected, BasicCheckResult), "not a BasicCheckResult: %r" % expected
        
            msg = "expected %s, but %%s is %%r" % repr(expected).replace('%', '%%')
            assert expected.status == actual.status, msg % ("status", actual.status)
        
            diff_idx = len(os.path.commonprefix((expected.infotext, actual.infotext)))
            diff_msg = ", differing at char %r" % diff_idx
    >       assert expected.infotext == actual.infotext, msg % ("infotext", actual.infotext) + diff_msg
    E       AssertionError: expected BasicCheckResult(0, '[database] Last backup was at 1970-05-23 22:21:18 (46 y ago)', [PerfValue('seconds', 1455979122.0, None, None, None, None)], multiline=None), but infotext is '[database] Last backup was at 1970-05-23 22:21:18 (49 y ago)', differing at char 52

How do I solve that? The code produces a variable timestamp (like "49 y ago" or "243 m ago") but the unit test compares with a fixed string. So every time the test runs it gets a different output and the test will always fail (?).

**Comment by jherbel** [comment]
For such cases, there is the option to fix the time to a certain value via the freeze_time variable, see e.g. [https://github.com/tribe29/checkmk/blob/master/tests-py3/unit/checks/generictests/datasets/oracle_instance_regression.py](https://github.com/tribe29/checkmk/blob/master/tests-py3/unit/checks/generictests/datasets/oracle_instance_regression.py)

To make this work, you first specify a fixed time using freeze_time = ... and then you run regression.py again, such that your expected test results are now based on the the fixed time you specified. That should do the trick.

**Comment by gurubert** [comment]
> For such cases, there is the option to fix the time to a certain value via the freeze_time variable, see e.g. https://github.com/tribe29/checkmk/blob/master/tests-py3/unit/checks/generictests/datasets/oracle_instance_regression.py

Ah, great. Thank you.

> To make this work, you first specify a fixed time using freeze_time = ... and then you run regression.py again, such that your expected test results are now based on the the fixed time you specified. That should do the trick.

How do I run `regression.py`?

**Comment by jherbel** [comment]
> How do I run `regression.py`?

This is described here: [regression.py](https://github.com/tribe29/checkmk/blob/master/tests-py3/unit/checks/generictests/regression.py), use something like 
`py.test -T unit tests/unit/checks/generictests/regression.py --datasetfile ~/tmp/example.py`

Alternatively, you can also replace the timestamps in tests-py3/unit/checks/generictests/datasets/mssql_backup_regression.py manually.

**Comment by gurubert** [comment]
I am closing this PR an will continue in PR #161

**Pull request closed without merging**
