### PR TITLE
Windows Agent: Replace mk_mysql.vbs with mk_mysql.ps1

### PR DESCRIPTION
**Pull request by victorwitkamp**

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Victor, 
thank you for your PR. Unfortunately, we cannot merge this for two reasons:

1. Some frequently used features of PS are available only from PS 3.0 onwards and we have to stay compatible with older systems.
2. We are anyway planing to replace this plugin with a Python script, s.t. we can use the same script for Linux and Windows.

Best
Jörg

**Comment by Yogibaer75** [comment]
> 1. Some frequently used features of PS are available only from PS 3.0 onwards and we have to stay compatible with older systems.
PowerShell 3.0 is the oldest supported version of PowerShell

**Comment by svenpanne** [comment]
> > 1. Some frequently used features of PS are available only from PS 3.0 onwards and we have to stay compatible with older systems.
> 
> PowerShell 3.0 is the oldest supported version of PowerShell

Alas, it is quite irrelevant for us what Microsoft considers "supported" or not, there are tons of Windows XP clients out there which need to be monitored. We can't tell our customers how to manage their fleet of machines, and lots of bigger companies are still stuck with XP/Vista/Server 2003.

PowerShell 1.0 was shipped with XP SP1 and Vista, PowerShell 2.0 with XP SP3 and Vista SP1. For Windows Server 2003 you need SP2 and an additional installation to get PowerShell 2.0. AFAIK, there is no PowerShell 3.0 for these systems, and even for 2.0 you need service packs/additional installations. so you can't rely on that 100%. Portable scripting for Windows is actually a valley of tears...

Perhaps we discontinue support for the versions some day, but AFAIK we don't have a roadmap for that yet.

**Comment by Yogibaer75** [comment]
> and lots of bigger companies are still stuck with XP/Vista/Server 2003.
> 
> PowerShell 1.0 was shipped with XP SP1 and Vista, PowerShell 2.0 with XP SP3 and Vista SP1. For Windows Server 2003 you need SP2 and an additional installation to get PowerShell 2.0. AFAIK, there is no PowerShell 3.0 for these systems, and even for 2.0 you need service packs/additional installations. so you can't rely on that 100%. Portable scripting for Windows is actually a valley of tears...

Then i must say the 1.6 agent you cannot run in a save way on such old systems. Also with 2008 the 1.6 has very big problems.
With 2003 the newest agent is 1.4 what should be used. With 2008 you have PowerShell 3 available.

If i speak for my big companies there is no one with 2003 anymore. Only a very small amount of 2008 are left there.

**Comment by victorwitkamp** [comment]
> > and lots of bigger companies are still stuck with XP/Vista/Server 2003.
> > 
> > PowerShell 1.0 was shipped with XP SP1 and Vista, PowerShell 2.0 with XP SP3 and Vista SP1. For Windows Server 2003 you need SP2 and an additional installation to get PowerShell 2.0. AFAIK, there is no PowerShell 3.0 for these systems, and even for 2.0 you need service packs/additional installations. so you can't rely on that 100%. Portable scripting for Windows is actually a valley of tears...
> 
> Then i must say the 1.6 agent you cannot run in a save way on such old systems. Also with 2008 the 1.6 has very big problems.
> With 2003 the newest agent is 1.4 what should be used. With 2008 you have PowerShell 3 available.
> 
> If i speak for my big companies there is no one with 2003 anymore. Only a very small amount of 2008 are left there.
> 

Agreed. The companies I work with rarely use unsupported versions of Windows. Especially not on machines connected to a network. 

I also believe it would be wise to use PowerShell for monitoring Windows since it is made by the same company that made the Windows operating itself . I really hoped to see more of that in CheckMK. But by using Python to keep it compatible with Linux makes me concerned about the future for Windows compatibility in CheckMK and gives me a bit of the idea that Windows support could be dropped any time. Using Python on Windows is just adding extra layers for features that are already in PowerShell, which comes with every supported version of Windows.

**Pull request closed without merging**
