### PR TITLE
replacing cisco_asa_xxxsessions with cisco_asa_vpnsessions

### PR DESCRIPTION
**Pull request by thl-cmk**
Hi Joerg,

her is the pull request for the cisco_asa_vpnsessions check as replacement for cisco_asa_ipsecsessions, cisco_asa_svcsessions, cisco_asa_webvpnsessions and cisco_asa_sessions.include.

I had to recereate my fork after the problems with your repository from the weekend :-( 
The old request was #183.

Grettings,
Thomas

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Thomas,
as we discussed via email, this pull request has been merged, see werks #11150 and #11152.
Thank you for your contributions.
Best
Jörg

**Comment by thl-cmk** [comment]
Hi Jörg,

i am happy :-)

Only one thing to reconsider: the session type SVC is technically correct, but in the ASA mgmt GUI and in the CLI it's  most of the time called AnyConnect and i think most of the admin's don't have a real clue what SVN is.

The Second thing what for AnyConnect speaks is, if you add Summary as Session type then you have Summary at the bottom of the VPN Session items and not in the middel.

Greetings,
Thomas

here the "show vpn-sessiondb" command from a ASA device:

```
fw01# sh vpn-sessiondb ?

  anyconnect       AnyConnect sessions
  detail           Show detailed output
  failover         Failover IPsec sessions
  full             Output formatted for data management programs
  index            Index of session
  l2l              IPsec LAN-to-LAN sessions
  license-summary  Show VPN License summary
  ospfv3           OSPFv3 IPsec sessions
  ra-ikev1-ipsec   IKEv1 IPsec/L2TP-IPsec Remote Access sessions
  ra-ikev2-ipsec   Generic IKEv2 IPsec Remote Access sessions
  ratio            Show VPN Session protocol or encryption ratios
  summary          Show VPN Session summary
  vpn-lb           VPN Load Balancing Mgmt sessions
  webvpn           WebVPN sessions
  |                Output modifiers
  <cr>
```

**Comment by jherbel** [comment]
Hi Thomas,

that's nice to hear :)

Concerning SVC vs. AnyConnect, since I am not a network admin myself, I was never certain whether there are other Cisco clients besides AnyConnect that would also be included in SVC. Is AnyConnect the only one?

Best
Jörg

**Comment by thl-cmk** [comment]
at least from Cisco, AnyConnect is the one and only VPN client to day. It support two modes, SSL (SVC) VPN and IKEv2/IPSec VPN. So I think a good compromise would be "AnyConnect SVN".
 This has the correct technical term (SVN) and is admin frendly ;-)

/Thomas

**Comment by jherbel** [comment]
Sorry, now I am completely confused :D Do you really mean "AnyConnect SVN" or rather "AnyConnect SVC"?

**Comment by thl-cmk** [comment]
SVC is correct, of course. Even I am not used to this term, and I use it every day ;-)

**Comment by jherbel** [comment]
Hi Thomas,
the service name has been changed to "AnyConnect SVC" (werk #11154), this will be available shortly.
Best
Jörg

**Pull request closed without merging**
