### PR TITLE
Begining of french translation effort for review

### PR DESCRIPTION
**Pull request by guillaume-durville**
French native working on Check_MK daily for Faurecia (currently). Speaks
english fluently, 9 years of german - not fluent but can read most.

Please let me know if this is an appropriate method or if I need to wait
completion of the entire translation.

Some remarks :
- typical french punctuations rules are applied, for example spacing
  around ":"
- accents on uppercase letters are applied, as per the standard
- most monitoring concepts or concepts linked to Check_MK are not
  translated, except for now the word "monitoring". "check" stays "check".
- main difficulty is to go around masculine and feminine in some cases and
  to manage small translation bits that have no particular context
- some parts of the german and english translation vary slightly in
  meaning
- technical terms outside of Check_MK like "container" have been
  translated according to the french standard for that technology
- the concept of "ackwnoledgment/acknowledged" is hard to translate to
  french directly. I opted to use "traité/non-traité" for now, but that
  can probably be made better.
- depending on context, monitoring is either translated or not if it makes
  sense to
- some parts of the translation are unsure, for the following lines : 130,
  302, 328, 441 , 477, 510, 521, 673, 694, 855,866. They either lack
  context or don't feel like it's the best possible translation

### CODE REVIEW

**Comment by LarsMichelsen** [comment]
Hi ,

thanks for your work so far!

It looks like you've taken the German translation as a basis. That's not the best start from my point of view, because now you have a mix of German and French GUI. It would be better if you started with an empty translation. So the GUI would show English texts. As you progress with your translation, more and more texts would be shown in French.

Someone else can also search for untranslated texts (msgstr "") in this way, which would make the collaboration much easier.

Managing po files is a pain directly in a text editor, especially in case multiple users work together on a single file. There are a lot of tools out there which would make this easier. What do you think about poeditor.com as platform? We already have an experimental account there. I could send you an invitation to try using the platform for your work.

Please also check the header: "Language: de\n". This should be updated to fr.

**Comment by guillaume-durville** [comment]
Hello lars,

No problem, this is a small bit and you guys are putting in serious and admirable work.

>It looks like you've taken the German translation as a basis. 

Yeah I copied the file were I found it to be honest, and I was thinking that context would be precious since on small bits of texts, sometimes it can be nice to have two translations to give more info, especially since I would assume that it was validated (since it's the master). I was of course relying on the english meaning when in doubt.

> That's not the best start from my point of view, because now you have a mix of German and French GUI. It would be better if you started with an empty translation. So the GUI would show English texts. As you progress with your translation, more and more texts would be shown in French.

I completely understand this problem, and I think you're definitely right, especially in the context of this : 

>Someone else can also search for untranslated texts (msgstr "") in this way, which would make the collaboration much easier.

>What do you think about poeditor.com as platform? We already have an experimental account there. I could send you an invitation to try using the platform for your work.

Don't know the tool, but ready and eager to work on it !

Currently I've spent something approx 2/3 hours right now for around 1000 lines worth of .po file, I guess that's a 100/150 hours job or something like that to have a working translation around.

Cooperation with other translators would be also appreciated as a second set of eyes can help clear out issues stemming from a single translator.

Have a good start of the week.

Feel free to close this PR if you want me to work on the .po editor instead or on a clean po without german.

Guillaume

**Comment by guillaume-durville** [comment]
Did the switch to the POEditor, very nice tool. Updated up to were I was on the PR.

Have a good start, thanks again.

Guillaume

**Comment by LarsMichelsen** [comment]
Nice 👍

**Pull request closed without merging**
