### PR TITLE
[Mac OSX Agent] network information (interfaces, speed)

### PR DESCRIPTION
**Pull request by corriou**
Adds network information.
Based on Wood_Adam_1528's idea : https://forum.checkmk.com/t/check-mk-english-monitoring-mac-osx/7301/2
No need to instal further tools, no sudo.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello corriou,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4465

**Comment by rawiriblundell** [comment]
Hi, this has already been proposed in a similar way in #145.  I've merged and improved both approaches in 36c7773.  You may like to copy some of the stuff I've done into this.  Cheers!

**Comment by doctore74** [comment]
works great! Thanks!

**Comment by Notausstieg0309** [comment]
works great on my mac mini's!

**Comment by mo-ki** [comment]
Believe it or not: This will be merged!

**Pull request closed without merging**
