### PR TITLE
support standard SATA drives in smart checks

### PR DESCRIPTION
**Pull request by jakkul**
This small change will enable normal SATA drives checking. Checked on everything else I have whether this still works. Needs checking on megaraids etc.

### CODE REVIEW

**Comment by jherbel** [comment]
You wrote 
> Needs checking on megaraids etc
Did you do that?

**Comment by jakkul** [comment]
yes. This patch does not conflict with megaraids. I did not check on systems with 3ware cards that require tw_cli - do not have such a system, but as far as I know smartctl, this should work no issue.

**Comment by jherbel** [comment]
I discussed this internally, unfortunately we cannot merge this. The reason is that this would require too much testing from our side for a PR, sorry for that.
Best, Jörg

**Comment by jakkul** [comment]
Well. OK. I understand. I'll try to publish separate smart sata check plugin that is compatible with this one so anyone that wants to monitor standard sata drives will be able to do it.

**Pull request closed without merging**
