### PR TITLE
mk_postgres: Bugfix for missing agent sections

### PR DESCRIPTION
**Pull request by Rendanic**
The Check_MK services creates a WARN with 'Missing
agent sections' from Agent when the PostgreSQL Cluster
has been stopped.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Thorsten,

thank you for this fix. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-2922

**Comment by LarsMichelsen** [comment]
Short update:

1. We had to change the history of our repository which made your PR not
   mergable anymore. We took the time to rebase your branch on top of
   the current master to resolve the situation.

   If you want to proceed with your work locally, your will have to update
   your local branch. You should be able to update it with:

   git pull --rebase

2. We have added tests to Travis-CI which will now run parts of our test
   suite on your changes (in case it's based on the master branch). In
   Case Travis finds issues, they will have to be fixed.

   Have a look at our new contribution guidelines for further information:

   https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md

**Comment by Rendanic** [comment]
I have no clue how to fix this, because it won't  work...
I'll close this PR and open a new one.

**Comment by jonaskluger** [comment]
Issue got resolved.
https://checkmk.com/check_mk-werks.php?werk_id=10439

**Pull request closed without merging**
