### PR TITLE
cisco_wlc new firmware sysObjectID

### PR DESCRIPTION
**Pull request by gurubert**
Make SNMP scan function work for new firmware version of WLAN controller

### CODE REVIEW

**Comment by thl-cmk** [comment]
Hi Robert,

might be a good idea to change the scan function from sysObjectID to sysDescr so we don't have to change the Cisco WLC checks every time Cisco comes up with a new controller.

I use in my WCL checks this snmp scan function:

`
'snmp_scan_function': lambda oid: oid('.1.3.6.1.2.1.1.1.0') == 'Cisco Controller',
`

This will catch at least all AirOS based Cisco WLCs.

Greetings,
Thomas

**Comment by gurubert** [comment]
Hi @thl-cmk,

I have seen your check. I have a feeling that sysDescription is bot reliable enough to detect the device correctly. I had support cases where the customer was able to change it via management gui and wondered why checkMK was not able to monitor the device.

**Comment by thl-cmk** [comment]
@gurubert 
ok. I don't had this yet. If so of course the sysObjectID is better (or mor save ;-) ) and we need to change the check all the time.

**Comment by jherbel** [comment]
Hi Robert,
thank you for this PR. We will have a look and decide if we can merge it.
Best regards
Jörg
Internal reference: CMK-5355

**Comment by edeka-spatt** [comment]
Please also add the new Cisco 9800 #254

**Comment by mo-ki** [comment]
Hi Robert,

Apparently this is obsolete; `.1.3.6.1.4.1.9.1.2530` is now discovered.

Cheers,
Moritz

**Pull request closed without merging**
