### PR TITLE
cisco_ip_sla: Fixed detection of some cisco models

### PR DESCRIPTION
**Pull request by Bastian-Kuhn**
With this fix, the following Models will be supported:
 - Cisco ASR1001-X
 - Cisco ASR1001-HX

### CODE REVIEW

**Comment by thl-cmk** [comment]
@Bastian-Kuhn please have a look at [2.0.0p9 CEE - SNMP scan not detecting Cisco SLAs on Cisco 4k series router](https://forum.checkmk.com/t/2-0-0p9-cee-snmp-scan-not-detecting-cisco-slas-on-cisco-4k-series-router/27094/3) in the CMK forum.

There is a posible fix for this check, that will not always need adding OIDs to the snmp detection for every (new) device. Maybe you can use this.

cheers
Thomas

**Comment by jherbel** [comment]
Hi @thl-cmk, your suggestion
```
"snmp_scan_function": lambda oid: "cisco" in oid(".1.3.6.1.2.1.1.1.0").lower()
                                      and "ios" in oid(".1.3.6.1.2.1.1.1.0").lower()
                                      and oid(".1.3.6.1.4.1.9.9.42.1.2.2.1.37.*"),
```
looks promising to me. @Bastian-Kuhn, does it work for you?

Is there any particular reason why we should check specifically for ".1.3.6.1.4.1.9.9.42.1.2.2.1.37.*" and not e.g. for ".1.3.6.1.4.1.9.9.42.1.2.9.1.10.*"?

**Comment by thl-cmk** [comment]
@jherbel there was no special reason to use ".1.3.6.1.4.1.9.9.42.1.2.2.1.37.*" except to use one OID that is already used in the check. ".1.3.6.1.4.1.9.9.42.1.2.9.1.10.*" will also do fine I think.

**Comment by Bastian-Kuhn** [comment]
I changed it like suggested and will come back after successful test.

**Comment by Titan-C** [comment]
Hi @Bastian-Kuhn, Did you  test it? Does it work for you? Can you fix the formatting so that it passes the Tests on Github?

**Comment by jherbel** [comment]
Closed this due to inactivity

**Pull request closed without merging**
