### PR TITLE
Convert to 2-space/soft-tab indenting as per style guide

### PR DESCRIPTION
**Pull request by rawiriblundell**
Hi,
This one looks like a lot, but it's just another simple change.  This one converts indenting to two space/soft tab based.

Some advantages are:

* Closer adherence to 80 column width, which is useful for debugging via serial management or vm console interfaces.
* Familiarity with languages like YAML that have stricter indenting rules

See, also: https://google.github.io/styleguide/shell.xml?showone=Indentation#Indentation

Rawiri

### CODE REVIEW

**Comment by LarsMichelsen** [comment]
I propose to make the following exceptions from the style guide:

- Instead of 2 spaces use 4 spaces per level
- Instead of 80 a line length of 100 is allowed

We also use these rules for the other languages (python, c++).

**Comment by rawiriblundell** [comment]
Hi Lars,
4/100 should be mostly fine for Linux (except for obvious cases such as the aforementioned vm console access, OOB access e.g. ilo/drac/etc and so on), but speaking from experience administrating both HPUX and Solaris, this is a decision that might cause some annoyance for any sysadmin trying to trace issues with the agent script.  Trust me, diagnosing shell script issues via an HP 700/96 interface at 4am in a chilly DC is not improved by the knowledge that the script developer was comfortable :)

Personally, I'm happy either way, what matters more to me is consistency.  Just keep in mind that shell code has a tendency to drift right very quickly, and unlike other languages it isn't flush with ways to minimise that drift in every instance, so it can be somewhat horizontally unfriendly.

So if you're happy with 4/100, then I'm happy with 4/100.  I do think that some additional guidelines need to be made in the instance of shell code, regardless of whether 2/80 is selected, or 4/100, or tabs/240, or tabs+3/60 or whatever.  Things like:

* If your code is between 80-100 characters in length, consider refactoring it or making it into a function
* If your code exceeds 100 characters in length, you must either make it a function or leave a comment above the code explaining why it cannot be refactored
* If you are nesting more than 3 levels, you should consider refactoring your code

There may also be situations where an indent might *need* to be considered needless, and so the inside block of code can remain un-indented if required.  I have found myself in this situation a lot recently but I can't for the life of me think of a real world example, so I'll just make one up:

Let's say you have a loop within a subshell for some reason:

```
# Use a subshell so that we return to the invoking directory when complete
(
    cd /tmp/something || return 1
    for blah in blah; do
        [some block of legitimate code here that exceeds 100 characters]
    done
)
```

In some instances, it might be necessary to flatten that:

```
# Use a subshell so that we return to the invoking directory when complete
(
cd /tmp/something || return 1
for blah in blah; do
    [some block of legitimate code here that no longer exceeds 100 characters]
done
)
```

Thoughts appreciated

Rawiri

**Comment by LarsMichelsen** [comment]
It would be nice if you could make life easier for the poor admins at their 80-column consoles in refrigerated data centers ;-).

However, we should concentrate on the main use cases with that piece of code, and 100 columns /4 spaces is more appropriate. Please update your PR, so that we can merge it.

**Comment by rawiriblundell** [comment]
Hi Lars, I firmly disagree about 4/100 being appropriate in this instance, however in the interests of getting more important things sorted out, I'll defer all responsibility and blame to you :)

I've reverted the change and fixed the obvious instances of 3 space indentation, hard tabs and I've wrapped some of the longer lines.  The script still violates 100 columns, but those should be either fixed or explained with subsequent refactoring.

Rawiri

**Comment by rawiriblundell** [comment]
Hi,
can we get this merge done?  It looks like you guys have gone radio silent for a few days...

Rawiri

**Comment by 7omb** [comment]
Hi Rawiri,
sorry for the late reply. The review was lost in vacation. The PR is now merged.

**Pull request closed without merging**
