### PR TITLE
added Oracle 19c support

### PR DESCRIPTION
**Pull request by OzZyHH**
This commit adds Oracle Database version 19c support. 
I tested this change on our site and it works flawlessly

### CODE REVIEW

**Comment by godspeed-you** [comment]
Hi,
thank you for this pull request. We need to discuss that internally and will then possibly merge your commit.

Please be aware that this can take some days since some of the responsible people are on vacation. :)

**Comment by Rendanic** [comment]
The PR looks fine for me. This could be merged as a Werk to 1.5.

**Comment by LarsMichelsen** [comment]
:+1:

**Comment by godspeed-you** [comment]
I finally merged this commit. It will be here in the mirror soon.

**Pull request closed without merging**
