### PR TITLE
port checkpoint_connections to new api and add peak + maximum values as well as relative thresholds

### PR DESCRIPTION
**Pull request by gradecke**
Checkpoint Connections ported to new api (mostly to get the hang of it.) and included the possibility to set thresholds in percentage, based on the maximum number of open connections that most checkpoint firewalls provide.

### CODE REVIEW

**Comment by gradecke** [comment]
ah - i forgot, on my test box I needed to delete the old share/check_mk/checks/checkpoint_connections for this to work, is that the proper way of doing it?

**Comment by jherbel** [comment]
Hi,
thank you for this PR. Yes, deleting the old file under checks/ is the way to go. However, this PR is too large. You are doing two things at once: migration and extending the functionality. Please split this up and do the two steps separately.
Best
Jörg

**Comment by gradecke** [comment]
Hi Jörg,
thanks for the quick reply. I knew that in theory every PR should be as atomic as possible, but in this case it seemed to make little sense to me as about 90% of the changed lines are because of the added features. So if I break this up into to PRs the second one (adding peak/maximum features) is still about the same size so it doesn't really save you any time reviewing it, and the first one (just porting to 2.0) is just extra work for me - or am I missing some other reasoning here?

**Comment by jherbel** [comment]
The point is reviewability. It is much easier and safer to review two separate commits, where one does not add any new functionality but instead only does the migration and the other one adds actual new functionality.

**Comment by gradecke** [comment]
hm - it still feels like you'll have to look at more changes in sum, but oh well, #316 has been created for the port to 1.0 first

**Comment by thl-cmk** [comment]
Hi,
the warn/crit against percentage of fwConnTableLimit will not allways work. 
fwConnTableLimit can be zero (0) if the connection table limt is automaticaly adusted (this is the default).

Greetings,
Thomas

**Comment by gradecke** [comment]
@Thomas/thl-cmk: good point. That would mean keeping the default at the pre defined absolute limits of 40000,50000 - what would be the best (most intuitive, least likely to cause false-negatives) way of handling it if a user blindly sets a relative limit, while no fwConnTableLimit is set? Presume a 50k connTableLimit and tell the user about it? Apply no limit? I'm leaning heavily towards the 50k limit, as I always rather have an alert that where I can then go back and change the threshold instead of a check that defaults to "OK". Any other views on that :)?

**Comment by thl-cmk** [comment]
After a short look to actual datasheets of the small CP appliances (like the 1530) the have a connection limit over all of 500K concurrent connections (on the midsized appliances it is from 2M upwards). So 50K sounds pretty save in terms of warning early :-). I would alert on a relative low level (even if fwConnTableLimit not 0), and force the admin to set a level that suits his environment. Let say my appliance can easily handle 2M connections but in my environment I have usualiy only 50K connections, I would have a warning on 60K upper limit and 10K lower limit. So i get not only a alert on problems with the appliance capacity but also on unusual high/low connection numbers.

Greetings,
Thomas

**Comment by gradecke** [comment]
This is now split into #316 and #337

**Pull request closed without merging**
