### PR TITLE
REDIS: Adding detection of not running instances

### PR DESCRIPTION
**Pull request by m3rlinux**
With these commit the redis check can now detect a not running instances

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, I guess that your master branch is not up to date, since you certainly don't want to change 2798 files. You could try re-basing onto the current master, maybe that would help.

**Review by jherbel — CHANGES_REQUESTED** [review]
see above

**Comment by m3rlinux** [comment]
> Hi, I guess that your master branch is not up to date, since you certainly don't want to change 2798 files. You could try re-basing onto the current master, maybe that would help.

Yes! That is becouse the first time I forked the branch 1.6.0.
I tryed to rebase but I didn't to manage because a lot of conflict.
Can you suggest me a fast way to update my master?
Many thanks for your help.

**Comment by jherbel** [comment]
Probably the best way is to simply fork off from the current master and re-implement your changes, maybe you can cherry-pick them. I will close this PR for now, feel free to open a new one once you have resolved this.

**Pull request closed without merging**
