### PR TITLE
Honor elphase state map in raritan_px_outlets check

### PR DESCRIPTION
**Pull request by jplitza**
## General information

The check for monitoring Raritan PX outlets currently ignores the "Map device state" parameter of the "Parameters for input phases of UPSs and PDUs" ruleset.

## Proposed changes

This simple renaming keeps the old behaviour if this parameter is unset (albeit changing output slightly).

### CODE REVIEW

**Comment by kain88-de** [comment]
Hi @jplitza I would like to merge this. Do you have an snmpwalk you can share so I can add a test for your change?

**Comment by jplitza** [comment]
Sure, here's the subtree relevant to the check: [raritan_px_walk.txt](https://github.com/tribe29/checkmk/files/9971361/raritan_px_walk.txt)
I snug in a small addition in a second commit: Showing the outlet label if available. If you want purely the fix, simply ignore the second commit.

**Comment by kain88-de** [comment]
Can you send me a complete walk. I cannot test the walk against a site if the system identifier OID, .1.3.6.1.2.1.1.1.0,  is missing.

**Comment by jplitza** [comment]
I hope I managed to scrub any identifying information: [raritan_px_walk.txt](https://github.com/tribe29/checkmk/files/10023814/raritan_px_walk.txt)

**Comment by kain88-de** [comment]
Thanks. Sorry for not mentioning this earlier, we also have more secure/confidential ways to share files. 

The checks run on my test environment. I'll run this through our internal testing pipelines and review process. Should be merged soon.

**Comment by jplitza** [comment]
Thought you might want to use the walk for a test case or something like that, in which case it would be public anyway.

**Pull request closed without merging**
