### PR TITLE
Fortinet FortiSandbox System Inventory

### PR DESCRIPTION
**Pull request by OguzhanCicek**
This PR adds SW inventory for the OS Version of Fortinet FortiSandbox Systems

### CODE REVIEW

**Comment by OguzhanCicek** [comment]
I have seen that operating system inventories usually show TYPE and VERSION. In my case there was no data that i could use as TYPE. Is this ok?

**Comment by mo-ki** [comment]
Looks good!
Can you add a small unit test? See tests/unit/cmk/base/plugins/agent_based/test_inv_oracle_tablespaces.py for reference.
I don't know, what the OID you are processing contains, but you should make sure the attributes do contain the name of the OS as well as the version. (Only "3.23" without context would be weird. But maybe that's already the case?)

**Review by jherbel — APPROVED** [review]

**Comment by jherbel** [comment]
Hi, this looks good now and is ready for merging. I would suggest that you take care of 
https://github.com/tribe29/checkmk/pull/295
https://github.com/tribe29/checkmk/pull/301
next, since these also belong to the HW/SW inventory. I will afterwards merge these 3 PRs.

**Comment by jherbel** [comment]
I just merged this, thank you very much!

**Pull request closed without merging**
