### PR TITLE
removed useless cluster inventory data if no cluster is present

### PR DESCRIPTION
**Pull request by Yogibaer75**
As the title says only inventory cluster if cluster is present.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Andreas,
after talking to a colleague, we decided that we cannot merge this PR. With your change, the corresponding inventory entry exists only for cluster hosts. However, we think that it should also be explicitly visible if a host is not a cluster.
Best regards
Joerg

**Comment by Yogibaer75** [comment]
> Hi Andreas,
> after talking to a colleague, we decided that we cannot merge this PR. With your change, the corresponding inventory entry exists only for cluster hosts. However, we think that it should also be explicitly visible if a host is not a cluster.
> Best regards
> Joerg

The problem is this entry is not configurable and if you have some thousand containers in a K8S environment every container has a very annoying entry for "Application -> Check MK -> Cluster -> No Cluster" as the important entries are also in this tree you have to deal with this spam.
This cluster entry is a good example that something is implemented without a view to the real practice.
If it is done with a normal inventory check then it can be modified but it is hard coded for every host.

It would be nice if there is a small discussion possible with the "inventor" of this feature.

best regards
Andreas

**Comment by jherbel** [comment]
Ok, fair enough. The hosts you are talking about are piggyback-hosts, right?

**Comment by Yogibaer75** [comment]
Yes all piggyback hosts get also this inventory entry.

**Comment by LarsMichelsen** [comment]
The flag was initially introduced to be able to create views with

a) a painter showing whether or not the host is a real or a cluster host.
b) a filter providing the option to filter a host view by this attribute

Since the information was also requested to be in the HW/SW inventory tree the things were realized in this way.

--

> This cluster entry is a good example that something is implemented without a view to the real practice.

In fact, the feature was built for practical use cases. It may not be relevant for you or many users, but there were at least a few use cases out there. However, I clearly understand that this information, if you don't have the need for the above things, may be irrelevant or annoying.

> If it is done with a normal inventory check then it can be modified but it is hard coded for every host.

What do you mean? How could you or other users do this?

Would it be an option for you to use the "Permitted HW/SW inventory paths" of the contact groups to hide the paths from your users?

So what else could we do about this? Would have various ideas about this, among other things:

- make inventory plugins generally disableable and move the feature to a plugin
- Remove the feature completely from the inventory, make a custom host attribute out of it, and use it to build the above views

**Comment by Yogibaer75** [comment]
Thanks Lars for the explanation. 
> > If it is done with a normal inventory check then it can be modified but it is hard coded for every host.
> 
> What do you mean? How could you or other users do this?

The best way would be if this is not hard coded inside the core of the inventory system.
If it is a normal plugin then an overwrite or something like this would be easier.

> Would it be an option for you to use the "Permitted HW/SW inventory paths" of the contact groups to hide the paths from your users?

I don't know if this option is working. Is this also affecting the HW/SW check itself? I don't think so.
You see the inventory data show with 1 entry on every device also if there is nothing. That would be a little bit more strange then before.

> 
> So what else could we do about this? Would have various ideas about this, among other things:
> 
> * make inventory plugins generally disableable and move the feature to a plugin
That's what we already use for some of our own inventory plugins, big plugins for Cisco hardware where we decide with rule if the inventory should be used or not. It is like the deployment of agent plugins.
Example: https://thl-cmk.hopto.org/gitlab/checkmk/cisco/wlc/inv_cisco_wlc_clients/-/blob/master/web/plugins/wato/inv_wlc_clients.py

> * Remove the feature completely from the inventory, make a custom host attribute out of it, and use it to build the above views
Completely remove would be only the "last resort" ;) If someone is using it then i don't want to forbid it.

In the end the disable option would be the option what would keep the current state for every one who uses it now and all other can disable it if not wanted/needed. Also for other inventory plugins already in the system this would be a good way in the right direction. 

You can also call me if some more discussion is needed.

**Comment by LarsMichelsen** [comment]
> In the end the disable option would be the option what would keep the current state for every one who uses it now and all other can disable it if not wanted/needed. Also for other inventory plugins already in the system this would be a good way in the right direction.

I agree. So we would need the following things:

a) move cluster info to plugin.
b) rule chain to disable HW/SW inventory plugins.

However, I would actually make an incompatible change out of it and disable this plugin by default, as the majority of users are certainly not interested in this information.

**Comment by jherbel** [comment]
Following our discussion, I created two internal issues for this:
CMK-6722
CMK-6724
These tickets are in our planning queue and will be tackled at one point.

**Pull request closed without merging**
