### PR TITLE
adds a check for current

### PR DESCRIPTION
**Pull request by gurubert**
This adds a new check for current. The check function already had support for it.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Robert,

thank you for this commit. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3080

**Comment by gurubert** [comment]
Ups, this PR got bigger than intended.

**Comment by jonaskluger** [comment]
Hey Robert,
did you rebase your code to the head of the master branch?

**Comment by gurubert** [comment]
I really cannot remember…

**Comment by jonaskluger** [comment]
Hey Robert,
there seem to be files in the .bugs folder. I quess your branch is at an quite old state.
Just rebase it to the latest master head and hopefully everything's going to be fine!

Best,
Jonas

**Comment by LarsMichelsen** [comment]
Sorry, this mess was made necessary by a required force-push. We had to make some history adjustments to our Github repository (yes, you don't actually...).

To fix this, you would have to rebase your local clones to the upstream branch and skip all commits except your local commits.

**Comment by gurubert** [comment]
So this is why I get merge errors. Do you have any CLI examples to do that?

**Comment by LarsMichelsen** [comment]
Short update:

1. We had to change the history of our repository which made your PR not mergable anymore.

   I would've rebased your branch on top of the current master to resolve the situation, but I have no permission to update your branch.

   You will have to do this on your own. Easiest way is to force pull the current upstream master, then create a new feature branch and cherry pick your commit into that branch. Then you can push the new branch to your remote repository HeinleinSupport:dell_poweredge_amperage again to update this PR.

2. We have added tests to Travis-CI which will now run parts of our test suite on your changes (in case it's based on the master branch). In Case Travis finds issues, they will have to be fixed.

   Have a look at our new contribution guidelines for further information:

   https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md

**Comment by gurubert** [comment]
Hi @LarsMichelsen , I have invited you to our CheckMK repo, please feel fre to rebase it.

**Comment by LarsMichelsen** [comment]
thanks! done.

**Comment by anthonyh209** [comment]
Hi Robert,
I wanted to let you know that we have merged your changes to our master. We made small adjustments to your files but left most of the propositions unchanged. Please have a look at them. 

Thank you

**Comment by jonaskluger** [comment]
Issue solved

**Pull request closed without merging**
