### PR TITLE
multiple HOSTADDRESSES in Bash shell arrays

### PR DESCRIPTION
**Pull request by lambertlu**
To support check multiple HOSTADDRESSES arrays in the Bash shell.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello  lambertlu,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4438

**Comment by gurubert** [comment]
This can already be achieved by separating the HOSTADDRESSES with spaces. Why should the array be needed here?

**Comment by lambertlu** [comment]
Hi Gurubert,
Thanks for reply.
The white space does not work in Ubuntu server 18.04 x64 .

**Comment by rawiriblundell** [comment]
@lambertlu Can you please demonstrate the issue that you're having?  This might be best placed in the troubleshooting section of the checkmk forum rather than discussed via github...  Either way, I'm guessing a variable quoting issue...

**Comment by rawiriblundell** [comment]
@jonaskluger I vote that this PR be closed.  What has been suggested is already provided natively and by the dnsclient.cfg standard via a simple whitespace-delimited variable, and a more worthwhile update can be found here:

https://forum.checkmk.com/t/check-mk-english-dnsclient-plugin/12451

Whitespacing works fine and is portable when used as a var, I suspect that @lambertlu is experiencing a standard shell quoting issue.  Demonstrated via `dash`:

```
$ hosts="google.com yahoo.com"
$ for host in $hosts; do printf -- '======== %s ========\n' "${host}" && nslookup "${host}"; done
======== google.com ========
Server:	127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.167.78
Name:	google.com
Address: 2404:6800:4006:80a::200e

======== yahoo.com ========
Server:	127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	yahoo.com
Address: 98.137.11.164
Name:	yahoo.com
Address: 98.137.11.163
Name:	yahoo.com
Address: 74.6.231.21
Name:	yahoo.com
Address: 74.6.143.26
Name:	yahoo.com
Address: 74.6.231.20
Name:	yahoo.com
Address: 74.6.143.25
Name:	yahoo.com
Address: 2001:4998:124:1507::f000
Name:	yahoo.com
Address: 2001:4998:44:3507::8000
Name:	yahoo.com
Address: 2001:4998:24:120d::1:0
Name:	yahoo.com
Address: 2001:4998:24:120d::1:1
Name:	yahoo.com
Address: 2001:4998:124:1507::f001
Name:	yahoo.com
Address: 2001:4998:44:3507::8001
```

**Comment by Synss** [comment]
@rawiriblundell Thank you for following up on this.

**Pull request closed without merging**
