### PR TITLE
added option container_id:nodename_name to mk_docker.py plugin

### PR DESCRIPTION
**Pull request by pescobar**
I have many docker nodes running containers with identical name and this change in mk_docker.py allows to name every piggybacked container as nodename_name , being "nodename" the hostname of the machine running the docker daemon (and also the check_mk agent) and "name" the name of the container

I tried to use the option in Access to agents ➳ General settings ➳ Hostname translation for piggybacked hosts but it seems that I cannot add the nodename in a generic way. I asked about it in the mailing list: https://lists.mathias-kettner.de/pipermail/checkmk-en/2019-October/028898.html

This change doesn't change the default behavior of the plugin

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hey Pablo,

thank you for your pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Best
Jonas

Internal Reference: CMK-4015

**Comment by anthonyh209** [comment]
Hi @Pablo Thank you for your PR. We had an internal discussion concerning your suggestion and would require some further input from your side. Here are our discussed points:
- We believe that the node name is not suited to be included in the hostname
- Eventually, you could further elaborate on your decision to include this option (eventually any benefits we might have overlooked)
- The name configuration suggestion would be fine in a "normal"  setup but could eventually lead to confusions when a swarm setup is employed (frequent change of hostnames despite having the "same" container) 
- If you would like to search all containers which run on a specific node then making use of the labels would probably more appropriate

Please let me know your thoughts. We could try to find a solution together.

**Comment by pescobar** [comment]
hi @anthonyh209 , thanks for getting back to me about this PR and sorry for the late reply

The reason why I wrote this PR was because I am using check_mk to monitor an openstack cloud with dozens of hypervisors. All the hypervisors run one container for each of the cloud services and those containers have identical name. This was making quite difficult to identify in which host the service (the container) was running. I am not sure if I explained properly. Maybe with an image it's easier. See this screenshot of "all hosts" section in my check_mk instance with this PR applied. Here you can see that `bm-compute-XX-` is the hostname of the docker node running the docker daemon that actually hosts the containers. `bm-compute-xx` is the node running the check_mk agent where I do the "piggyback". Without my PR I was getting plenty of hosts in check_mk with identical name (e.g. dozens of check_mk hosts named `nova_libvirt`, one for each hypervisor) and there was no easy way to identify in which docker node the container was running. With my PR the host in check_mk is named `bm-compute01-lm-nova_libvirt` and this helps me to identify that check_mk is monitoring container `nova_libvirt` in server `bm-compute01-lm`

check_mk_all_hosts

I hope I could explain what was my motivation for this patch. 

Maybe there is a better alternative to achieve what I need without my patch? I would be happy to use the uptream check_mk version without any custom modification. I asked in the mailing list and I also tried the option `Hostname translation for piggybacked hosts` but this couldn't do what I needed. You can find more details here: https://forum.checkmk.com/t/check-mk-english-regex-example-to-rename-piggybacked-containers-to-nodename-containername/15945/2

regards,
Pablo

**Comment by LarsMichelsen** [comment]
Looks like a completely valid use case to me. I vote to implement it.

Maybe it's enough to start with a fixed combination of node name and container name, similar to what is done in the commit.

In the long run, it might even be better to allow some kind of templating here, with macros like the following:

$CONTAINER_ID$
$CONTAINER_ID_SHORT$
$CONTAINER_NAME$
$NODE_NAME$

Has the advantage that a user can flexibly choose the naming scheme (including separators).

When merging, however, the new option would also have to be taken into account in the valuespec of the Agent Bakery plugin.

**Comment by anthonyh209** [comment]
Hi Pablo, 
sorry for the late response. We had another round of discussion including Lars regarding this. While we believe that your PR suggests a valid approach, we ultimately decided not to implement it. Our reasoning points are based on the fact that the Piggyback translation is a bit more flexible: 

- You can define the prefix, suffix etc. yourself and it is not limited to the hostname
- This is also useful for the previously mentioned swarm environment where containers can jump between nodes
- It is not required to change configuration for the plugin on the hosts if you want to change the naming scheme
- This feature already exists and will be further improved in the near future with Macro functionality

I hope these points make our decision understandable

**Comment by pescobar** [comment]
hi @anthonyh209 , thanks for your reply

I agree that using the piggyback translation seems a better option. I tried it and the reason why I switched to this approach was because I didn't manage do what I needed using piggyback translation.

In a quick look at the code my understanding was that the translation is  done [here]( https://github.com/tribe29/checkmk/blob/master/cmk/utils/translations.py#L29) but as function `_translate` is not receiving the hostname of the machine running the docker daemon (nodename) I cannot add it using piggyback translation. Is that right or am I overseeing the right way to do it?

In case it can be done using piggyback translation could you share an example? I couldn't manage to find a working config using piggyback translation unless I write a specific rule for each of my docker hosts hardcoding the nodename which is not something very scalable with the amount of docker hosts I have.

**Comment by anthonyh209** [comment]
Hi Pablo, 

Yes you mention mostly valid points. The Piggyback translation for your use case is slightly more handy at the moment (meaning that you have to configure the rule for each host with the Condition at the lower section of this configuration rule). In my previous point, I mentioned that we will further improve the translation mechanism. Once implemented, the Macro option will require you to only specify this rule once. 

I hope this makes it more clear

**Comment by pescobar** [comment]
Thanks for the clarification. I will wait then until `$NODE_NAME` can be used in the piggyback translation macros. Indeed that's a better solution.

**Comment by pescobar** [comment]
@anthonyh209  @LarsMichelsen may I ask if this feature has been implemented upstream?

In case it's implemented, in which version? and is there any documentation available?

Thanks.

**Pull request closed without merging**
