### PR TITLE
Commend myhostname in /etc/postfix/main.cf

### PR DESCRIPTION
**Pull request by deatheibon**
Some mailservers rejecting mails with BOGUS HELO if you let myhostname = deadaf093c07 uncommeded.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello deatheibon,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4340

**Comment by mo-ki** [comment]
Hi @deatheibon,

I realize it has been ages. Is this still relevant? We believe the solution described [here](https://docs.checkmk.com/latest/en/managing_docker.html#_sending_notifications) 

> If the mail server expects a specific host name, add the following option: --hostname 'mymonitoring.mydomain.com'.

would be the better one, since we're not sure whether removing the `postconf -` could lead to problems in different setups.

**Comment by si-23** [comment]
Hi @deatheibon,
Is this still relevant? Or does the suggestion from my colleague work for you?

**Comment by deatheibon** [comment]
Hi, 

i think its still a problem this setup i was running at this time is still live with same fix. 
the problem with with --hostname is that the docker container is getiing a valid hostname then but in the docker image you have an overwrite for the hostname in postfix. 

under /etc/postfix/main.cf line: 

myhostname = deadaf093c07

so postfix is then greeting with this hostname which is treated as invalid from my mailserver no matter whats the hostname inside the checkmk docker container. So i think either just comment it out but yeah maybe this is causing problems on other setups or the entrypoint script sets the current conatiner hostname with postconf in this case the --hostname option should work.

**Comment by mo-ki** [comment]
Hi @deatheibon,

You are not going to believe this, but we'll be merging this shortly :-)

**Pull request closed without merging**
