### PR TITLE
Add new plugin for McAfee virus pattern age for both Virusscan and ENS

### PR DESCRIPTION
**Pull request by philrandal**
mcafee_av_client.ps1 checks both Virusscan and ENS DAT dates in registry.

Added comment in mcafee_av_client.bat informing users that it is restricted to Virusscan only

### CODE REVIEW

**Comment by philrandal** [comment]
This check should really be cached in the agent.  McAfee usually updates virus patterns once a day.

**Comment by jonaskluger** [comment]
Hello Phil,

thank you for this fix. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-2915

**Comment by LarsMichelsen** [comment]
Short update:

1. We had to change the history of our repository which made your PR not
   mergable anymore. We took the time to rebase your branch on top of
   the current master to resolve the situation.

   If you want to proceed with your work locally, your will have to update
   your local branch. You should be able to update it with:

   git pull --rebase

2. We have added tests to Travis-CI which will now run parts of our test
   suite on your changes. In case travis finds issues, they will have
   to be fixed.

   Have a look at our new contribution guidelines for further information:

   https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md

**Comment by jonaskluger** [comment]
Hey Phil,

we wanted to give you a heads up that we will start closing **stale & inactive** pull request from the beginning of next week.

Pull request that are pending because more information from the original contributor are needed or pull request that do not follow our contribution guidelines will be affected.

These pull request will  be closed after 14 days of inactivity.

This will help us staying up to date with the suggested improvements from the community.
We really appreciate your contribution to our code base! Thank you a lot from the team!

All the best
Jonas

**Comment by jonaskluger** [comment]
Closed due to inactivity.

**Pull request closed without merging**
