### PR TITLE
Prevent false SW RAID alerts in clustered setups, and from Netapp NFS shares with snapshots

### PR DESCRIPTION
**Pull request by troelsarvin**
In case of clustered servers where software RAIDs are part of
the clustered services, "Personalities" lines may appear multiple
times in agent output.
Without this change, there are false alerts about RAID failure in
that particular corner case.

I consider this a pure bugfix. And I believe this is internally in Tribe29 known as issue CMK-5226.

### CODE REVIEW

**Comment by Titan-C** [comment]
Hi, can you help us with an agent output were we can see how that input is messing up with our parser. In general "Personalities" don't play a role to our parser, we shouldn't need an extra statement to skip them, we need to make sure they don't sneak in while the instance is being parsed.

**Comment by troelsarvin** [comment]
Sorry for the delay, here's the <<<md>>> section of output from the two servers which form a fail-over cluster.

Server 1:
```
<<<md>>>
Personalities : [raid1] 
md2 : active raid1 dm-17[0] dm-12[1]
      4294834112 blocks super 1.2 [2/2] [UU]
      bitmap: 0/32 pages [0KB], 65536KB chunk

md0 : active raid1 dm-10[0] dm-16[1]
      4294834112 blocks super 1.2 [2/2] [UU]
      bitmap: 0/32 pages [0KB], 65536KB chunk

unused devices: <none>
```
Server 2:
```
<<<md>>>
Personalities : [raid0] 
md6 : active raid0 dm-17[0] dm-12[1]
      8589667328 blocks super 1.2 512k chunks
      
md5 : active raid0 dm-15[0] dm-13[1]
      8589667328 blocks super 1.2 512k chunks
      
unused devices: <none>
```

**Comment by troelsarvin** [comment]
Note: The pull request now also contains a fix for a false alert we have seen about NFS mounts related to snapshots.

I believe the server-side storage is a Netapp filer. It appears such a filer will sometimes export shares which are called (for example) /main_share_name/.snapshot/daily.2022-02-03_0010 and they appear in /proc/mounts for reasons which I don't understand. Anyway:

Such snapshot shares have a size of 0, and that confuses Checkmk, resulting in false alerts like these which claim that there is a Stale file handle (which is not the case):
sshot_false_nfs_alerts
With my fix to cmk/base/check_legacy_includes/network_fs.py, the alert becomes instead a warning about "Size of filesystem is 0 MB" which it should be.

This is a part of agent output's <<<nfsmounts>>> when such a snapshot share exists in /proc/mounts:
```
/shared/sharevol23/.snapshot/daily.2022-02-03_0010 ok 0 0 0 65536
```

So now my pull request contains fixes to two different issues. Is that a problem? If so, can you suggest how to do it instead?

**Comment by TLI29** [comment]
Hi troelsarvin,
we just look at your pull request. Can you please help us in separating the two different topics into separate pull requests and provide a test function with each PR? This would allow us to accept them.
Thanks, Thomas

**Comment by kain88-de** [comment]
@troelsarvin Sorry for the delayed answer. Are you still experience this problem in 2.1? We had some changes to clustering in this release, see the recent [conference talk](https://youtu.be/LM2asxj6YXs?t=1163) for details. 

About the netapp changes. Please move them to a separate PR so we can have a look at them.

**Comment by troelsarvin** [comment]
I have changed job and I don't have access to the system any more.

**Comment by kain88-de** [comment]
I did a closer check again. The clustering bug is fixed in 2.1 and later. We do not combine agent output on clustered hosts so the personalities line can never appear twice in an agent output that is processed by the check.

For the netapp check to ignore snapshot directories is a good idea. I'll track this separately internally and will fix it in our next sprint. 

Thanks for altering us about those issues and good luck in your new job.

**Pull request closed without merging**
