### PR TITLE
add 5 secs of timeout to connection

### PR DESCRIPTION
**Pull request by m3rlinux**

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, 
thank you very much for this PR. Except for bugfixes, we only merge PRs into the master branch (I am saying this because your PR is for the 1.6 branch). If you want, we can consider merging it into the master.
Best
Jörg

**Review by jherbel — APPROVED** [review]

**Comment by jherbel** [comment]
I just saw that you increased the timeout to 6 seconds. I guess that we could also merge this, however, this number is a bit random...Do 5 seconds work for you or do you need more?

**Comment by m3rlinux** [comment]
It's enough 5 secs.
I apologize for the inconvenient. It was just a "test commit", I'm learning how to work with Git and PyCharm.
Excume again.

**Review by jherbel — CHANGES_REQUESTED** [review]
See above

**Comment by jherbel** [comment]
Closed this due to inactivity.

**Pull request closed without merging**
