### PR TITLE
replacing cisco_asa_xxxsessions with cisco_asa_vpnsessions

### PR DESCRIPTION
**Pull request by thl-cmk**
Hi Jörg,

her is the pull request for the cisco_asa_vpnsessions check as replacement for cisco_asa_ipsecsessions,  cisco_asa_svcsessions, cisco_asa_webvpnsessions and cisco_asa_sessions.include.

This is my first pull request at all, so I hope I hav done it right ;-)

https://forum.checkmk.com/t/your-feedback-is-needed-checkmk-feature-pack-2/18440/8

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Thomas,
thank you for this, I will take a look.
Best
Jörg

**Comment by thl-cmk** [comment]
Hi Joerg,

what can i do to resolve this conflict?

Thanks,
Thomas

**Comment by jherbel** [comment]
Hi Thomas,
there is no need for you to resolve it. I will take care of the actual merge and resolve it in the process. Don't worry, this won't be an issue.
Best
Jörg

**Comment by jherbel** [comment]
Hi Thomas,
does this also work with Cisco Firepower? I am asking because it is included in the snmp_scan_function, but in your GitLab, you say that it is not fully tested.
Best
Jörg

**Comment by thl-cmk** [comment]
Hi Joerg,

it does work with Cisco Firepower devices, I just dont have enough devices to test with, only one installation at the moment.

Greetings
Thomas

**Pull request closed without merging**
