### PR TITLE
Fix detection for cisco_ip_sla on some devices

### PR DESCRIPTION
**Pull request by Bastian-Kuhn**
This commit adds a universal scan function which will detect all supported devices. 

Also see: https://github.com/tribe29/checkmk/pull/414

### CODE REVIEW

**Comment by scolakovic** [comment]
Hi Bastian,

Which devices weren't getting discovered? Can you share SNMP walks?

**Comment by Bastian-Kuhn** [comment]
Hi,

Sadly, can't share all information because of regulations, but at least some snippets:
Begin of the Walk:

```
.1.3.6.1.2.1.1.1.0 "43 69 73 63 6F 20 49 4F 53 20 53 6F 66 74 77 61 72 65 20 5B 41 6D 73 74 65 72 64 61 6D 5D 2C 20 41 53 52 31 30 30 30 20 53 6F 66 74 77 61 72 65 20 28 58 38 36 5F 36 34 5F 4C 49 4E 55 58 5F 49 4F 53 44 2D 55 4E 49 56 45 52 53 41 4C 4B 39 2D 4D 29 2C 20 56 65 72 73 69 6F 6E 20 31 37 2E 33 2E 33 2C 20 52 45 4C 45 41 53 45 20 53 4F 46 54 57 41 52 45 20 28 66 63 37 29 0D 0A 54 65 63 68 6E 69 63 61 6C 20 53 75 70 70 6F 72 74 3A 20 68 74 74 70 3A 2F 2F 77 77 77 2E 63 69 73 63 6F 2E 63 6F 6D 2F 74 65 63 68 73 75 70 70 6F 72 74 0D 0A 43 6F 70 79 72 69 67 68 74 20 28 63 29 20 31 39 38 36 2D 32 30 32 31 20 62 79 20 43 69 73 63 6F 20 53 79 73 74 65 6D 73 2C 20 49 6E 63 2E 0D 0A 43 6F 6D 70 69 6C 65 64 20 54 68 75 20 30 34 2D 4D 61 72 2D 32 31 20 31 32 3A 33 36 20 62 "
.1.3.6.1.2.1.1.2.0 .1.3.6.1.4.1.9.1.2348
.1.3.6.1.2.1.1.3.0 2513881376
.1.3.6.1.2.1.1.4.0 xyz@net.xyz
.1.3.6.1.2.1.1.5.0 xyz.com
.1.3.6.1.2.1.1.6.0 xyz-dc
.1.3.6.1.2.1.1.7.0 78
.1.3.6.1.2.1.1.8.0 0
.1.3.6.1.2.1.2.1.0 31
.1.3.6.1.2.1.2.2.1.1.1 1
.1.3.6.1.2.1.2.2.1.1.2 2
.1.3.6.1.2.1.2.2.1.1.3 3
.1.3.6.1.2.1.2.2.1.1.4 4
.1.3.6.1.2.1.2.2.1.1.5 5
.1.3.6.1.2.1.2.2.1.1.6 6
.1.3.6.1.2.1.2.2.1.1.7 7
.1.3.6.1.2.1.2.2.1.1.8 8
```

IP Sla Part on Same Device
```
.1.3.6.1.4.1.9.9.42.1.2.1.1.2.900 ##Back-up Line##
.1.3.6.1.4.1.9.9.42.1.2.1.1.2.901 ##Internet Connection##
.1.3.6.1.4.1.9.9.42.1.2.1.1.2.902 ## ICMP Jitter SLA ##
.1.3.6.1.4.1.9.9.42.1.2.1.1.3.900 
.1.3.6.1.4.1.9.9.42.1.2.1.1.3.901 
.1.3.6.1.4.1.9.9.42.1.2.1.1.3.902 
.1.3.6.1.4.1.9.9.42.1.2.1.1.4.900 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.4.901 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.4.902 16
.1.3.6.1.4.1.9.9.42.1.2.1.1.5.900 2
.1.3.6.1.4.1.9.9.42.1.2.1.1.5.901 30
.1.3.6.1.4.1.9.9.42.1.2.1.1.5.902 5
.1.3.6.1.4.1.9.9.42.1.2.1.1.6.900 3
.1.3.6.1.4.1.9.9.42.1.2.1.1.6.901 3
.1.3.6.1.4.1.9.9.42.1.2.1.1.6.902 30
.1.3.6.1.4.1.9.9.42.1.2.1.1.7.900 500
.1.3.6.1.4.1.9.9.42.1.2.1.1.7.901 500
.1.3.6.1.4.1.9.9.42.1.2.1.1.7.902 5000
.1.3.6.1.4.1.9.9.42.1.2.1.1.8.900 2
.1.3.6.1.4.1.9.9.42.1.2.1.1.8.901 2
.1.3.6.1.4.1.9.9.42.1.2.1.1.8.902 2
.1.3.6.1.4.1.9.9.42.1.2.1.1.9.900 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.9.901 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.9.902 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.10.900 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.10.901 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.10.902 1
.1.3.6.1.4.1.9.9.42.1.2.1.1.11.900 
.1.3.6.1.4.1.9.9.42.1.2.1.1.11.901 
.1.3.6.1.4.1.9.9.42.1.2.1.1.11.902 
.1.3.6.1.4.1.9.9.42.1.2.1.1.12.900 
.1.3.6.1.4.1.9.9.42.1.2.1.1.12.901 
.1.3.6.1.4.1.9.9.42.1.2.1.1.12.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.1.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.1.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.1.902 34
.1.3.6.1.4.1.9.9.42.1.2.2.1.2.900 "0A FB 05 15 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.2.901 "D0 43 DE DE "
.1.3.6.1.4.1.9.9.42.1.2.2.1.2.902 "0A FB 05 15 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.3.900 28
.1.3.6.1.4.1.9.9.42.1.2.2.1.3.901 28
.1.3.6.1.4.1.9.9.42.1.2.2.1.3.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.4.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.4.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.4.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.5.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.5.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.5.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.6.900 "00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.6.901 "00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.6.902 "0A FB 05 16 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.7.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.7.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.7.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.8.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.8.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.8.902 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.9.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.9.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.9.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.10.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.10.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.10.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.11.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.11.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.11.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.12.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.12.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.12.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.13.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.13.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.13.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.14.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.14.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.14.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.15.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.15.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.15.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.16.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.16.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.16.902 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.17.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.17.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.17.902 10
.1.3.6.1.4.1.9.9.42.1.2.2.1.18.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.18.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.18.902 50
.1.3.6.1.4.1.9.9.42.1.2.2.1.19.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.19.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.19.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.20.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.20.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.20.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.21.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.21.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.21.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.22.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.22.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.22.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.23.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.23.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.23.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.24.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.24.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.24.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.25.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.25.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.25.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.26.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.26.901 xyz-vrf-internet
.1.3.6.1.4.1.9.9.42.1.2.2.1.26.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.27.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.27.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.27.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.28.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.28.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.28.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.29.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.29.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.29.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.30.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.30.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.30.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.31.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.31.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.31.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.32.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.32.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.32.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.33.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.33.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.33.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.34.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.34.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.34.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.35.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.35.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.35.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.36.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.36.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.36.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.37.900 1
.1.3.6.1.4.1.9.9.42.1.2.2.1.37.901 1
.1.3.6.1.4.1.9.9.42.1.2.2.1.37.902 1
.1.3.6.1.4.1.9.9.42.1.2.2.1.38.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.38.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.38.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.39.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.39.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.39.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.40.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.40.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.40.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.41.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.41.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.41.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.42.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.42.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.42.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.43.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.43.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.43.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.44.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.44.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.44.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.45.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.45.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.45.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.46.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.46.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.46.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.47.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.47.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.47.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.48.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.48.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.48.902 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.49.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.49.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.49.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.50.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.50.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.50.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.51.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.51.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.51.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.52.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.52.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.52.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.53.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.53.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.53.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.54.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.54.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.54.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.55.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.55.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.55.902 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.56.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.56.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.56.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.57.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.57.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.57.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.58.900 3
.1.3.6.1.4.1.9.9.42.1.2.2.1.58.901 3
.1.3.6.1.4.1.9.9.42.1.2.2.1.58.902 3
.1.3.6.1.4.1.9.9.42.1.2.2.1.59.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.59.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.59.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.60.900 "00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.60.901 "00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.60.902 "00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.61.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.61.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.61.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.62.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.62.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.62.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.63.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.63.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.63.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.64.900 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.64.901 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.64.902 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.65.900 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.65.901 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.65.902 "00 00 00 00 00 00 "
.1.3.6.1.4.1.9.9.42.1.2.2.1.66.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.66.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.66.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.67.900 
.1.3.6.1.4.1.9.9.42.1.2.2.1.67.901 
.1.3.6.1.4.1.9.9.42.1.2.2.1.67.902 
.1.3.6.1.4.1.9.9.42.1.2.2.1.68.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.68.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.68.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.69.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.69.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.69.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.70.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.70.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.70.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.71.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.71.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.71.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.72.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.72.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.72.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.73.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.73.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.73.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.74.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.74.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.74.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.75.900 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.75.901 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.75.902 0
.1.3.6.1.4.1.9.9.42.1.2.2.1.76.900 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.76.901 2
.1.3.6.1.4.1.9.9.42.1.2.2.1.76.902 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.1.900 2147483647
.1.3.6.1.4.1.9.9.42.1.2.5.1.1.901 2147483647
.1.3.6.1.4.1.9.9.42.1.2.5.1.1.902 2147483647
.1.3.6.1.4.1.9.9.42.1.2.5.1.2.900 1
.1.3.6.1.4.1.9.9.42.1.2.5.1.2.901 1
.1.3.6.1.4.1.9.9.42.1.2.5.1.2.902 1
.1.3.6.1.4.1.9.9.42.1.2.5.1.3.900 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.3.901 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.3.902 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.4.900 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.4.901 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.4.902 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.5.900 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.5.901 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.5.902 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.6.900 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.6.901 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.6.902 2
.1.3.6.1.4.1.9.9.42.1.2.5.1.7.900 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.7.901 0
.1.3.6.1.4.1.9.9.42.1.2.5.1.7.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.1.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.1.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.1.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.2.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.2.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.2.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.3.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.3.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.3.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.4.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.4.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.4.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.5.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.5.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.5.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.6.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.6.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.6.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.7.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.7.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.7.902 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.8.900 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.8.901 0
.1.3.6.1.4.1.9.9.42.1.2.6.1.8.902 0
.1.3.6.1.4.1.9.9.42.1.2.7.1.1.900 2
.1.3.6.1.4.1.9.9.42.1.2.7.1.1.901 2
.1.3.6.1.4.1.9.9.42.1.2.7.1.1.902 2
.1.3.6.1.4.1.9.9.42.1.2.7.1.2.900 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.2.901 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.2.902 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.3.900 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.3.901 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.3.902 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.4.900 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.4.901 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.4.902 1
.1.3.6.1.4.1.9.9.42.1.2.7.1.5.900 20
.1.3.6.1.4.1.9.9.42.1.2.7.1.5.901 20
.1.3.6.1.4.1.9.9.42.1.2.7.1.5.902 20
.1.3.6.1.4.1.9.9.42.1.2.8.1.1.900 0
.1.3.6.1.4.1.9.9.42.1.2.8.1.1.901 0
.1.3.6.1.4.1.9.9.42.1.2.8.1.1.902 0
.1.3.6.1.4.1.9.9.42.1.2.8.1.2.900 15
.1.3.6.1.4.1.9.9.42.1.2.8.1.2.901 15
.1.3.6.1.4.1.9.9.42.1.2.8.1.2.902 0
.1.3.6.1.4.1.9.9.42.1.2.8.1.3.900 1
.1.3.6.1.4.1.9.9.42.1.2.8.1.3.901 1
.1.3.6.1.4.1.9.9.42.1.2.8.1.3.902 1
.1.3.6.1.4.1.9.9.42.1.2.8.1.4.900 1
.1.3.6.1.4.1.9.9.42.1.2.8.1.4.901 1
.1.3.6.1.4.1.9.9.42.1.2.8.1.4.902 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.1.900 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.1.901 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.1.902 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.2.900 
.1.3.6.1.4.1.9.9.42.1.2.9.1.2.901 
.1.3.6.1.4.1.9.9.42.1.2.9.1.2.902 
.1.3.6.1.4.1.9.9.42.1.2.9.1.3.900 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.3.901 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.3.902 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.4.900 1840
.1.3.6.1.4.1.9.9.42.1.2.9.1.4.901 1840
.1.3.6.1.4.1.9.9.42.1.2.9.1.4.902 0
.1.3.6.1.4.1.9.9.42.1.2.9.1.5.900 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.5.901 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.5.902 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.6.900 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.6.901 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.6.902 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.7.900 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.7.901 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.7.902 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.8.900 4400861
.1.3.6.1.4.1.9.9.42.1.2.9.1.8.901 4400324
.1.3.6.1.4.1.9.9.42.1.2.9.1.8.902 385466
.1.3.6.1.4.1.9.9.42.1.2.9.1.9.900 2147483647
.1.3.6.1.4.1.9.9.42.1.2.9.1.9.901 2147483647
.1.3.6.1.4.1.9.9.42.1.2.9.1.9.902 2147483647
.1.3.6.1.4.1.9.9.42.1.2.9.1.10.900 6
.1.3.6.1.4.1.9.9.42.1.2.9.1.10.901 6
.1.3.6.1.4.1.9.9.42.1.2.9.1.10.902 6
.1.3.6.1.4.1.9.9.42.1.2.9.1.11.900 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.11.901 2
.1.3.6.1.4.1.9.9.42.1.2.9.1.11.902 2
.1.3.6.1.4.1.9.9.42.1.2.10.1.1.900 1
.1.3.6.1.4.1.9.9.42.1.2.10.1.1.901 8
.1.3.6.1.4.1.9.9.42.1.2.10.1.1.902 1
.1.3.6.1.4.1.9.9.42.1.2.10.1.2.900 1
.1.3.6.1.4.1.9.9.42.1.2.10.1.2.901 1
.1.3.6.1.4.1.9.9.42.1.2.10.1.2.902 1
.1.3.6.1.4.1.9.9.42.1.2.10.1.3.900 0
.1.3.6.1.4.1.9.9.42.1.2.10.1.3.901 0
.1.3.6.1.4.1.9.9.42.1.2.10.1.3.902 0
.1.3.6.1.4.1.9.9.42.1.2.10.1.4.900 
.1.3.6.1.4.1.9.9.42.1.2.10.1.4.901 
.1.3.6.1.4.1.9.9.42.1.2.10.1.4.902 
.1.3.6.1.4.1.9.9.42.1.2.10.1.5.900 2513884781
.1.3.6.1.4.1.9.9.42.1.2.10.1.5.901 2513884788
.1.3.6.1.4.1.9.9.42.1.2.10.1.5.902 2513882361
.1.3.6.1.4.1.9.9.42.1.2.10.1.6.900 "0A FB 05 15 "
.1.3.6.1.4.1.9.9.42.1.2.10.1.6.901 "D0 43 DE DE "
.1.3.6.1.4.1.9.9.42.1.2.10.1.6.902 "0A FB 05 15 "

```

And here Checkmk after disabling this changes:

grafik

And with the Plugin:

grafik

**Comment by scolakovic** [comment]
I see the benefit of adding more devices to this check. I just want to make sure we don't lose the ones we already have.
@Bastian-Kuhn Why do you check 1.3.6.1.4.1.9.9.42.1.2.2.1.37.* (rttMonEchoAdminPrecision)?

**Comment by thl-cmk** [comment]
The devices the check is detecting to day are IOS (C891, Cat3560)/IOS-XE (ISR4331) devices. So there should be no risk to lose them.

**Comment by thl-cmk** [comment]
> Why do you check 1.3.6.1.4.1.9.9.42.1.2.2.1.37.*

there was no special reason to use 1.3.6.1.4.1.9.9.42.1.2.2.1.37 except it is used in the check anyway, any other IP SLA OID will do as well.

**Pull request closed without merging**
