### PR TITLE
add more downtime options

### PR DESCRIPTION
**Pull request by gurubert**
end a downtime at 10:00 the next day

or on the next monday resp the first monday after January 1st.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Robert,

thank you for this request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3178

**Comment by m4c3** [comment]
It would be great to have a setting to only display those enhanced downtime options

**Comment by makanakoeln** [comment]
Hi Robert,
we discussed this internally and decided not to implement it this way.
The time "10:00" is arbitrary, we could then implement 23 other times as well.

We see the need, but the options would have to be more flexible.

Best regards
Ronny

**Comment by gurubert** [comment]
Then let us make the configurable.

**Comment by godspeed-you** [comment]
Hi Robert,
Since we already have a configurable ending time, we would need a possibility to make that work with just one click (as it is now). I fully understand your point: Setting a downtime for today is maybe not very productive, because it is no help, if the downtime ends on Sunday 24:00 am or even on 31.12. 24:00. 

So what your PR would need to do:
* Figure out a reasonable expiration date for the next day
* One click as it is for similar shortcuts

As far as I can see know, it is not trivial to change the behavior as you suggest (and do not break anything). This would only be possible if we would also change the valuespecs for the forms and change the usage. E.g. if we would use the shortcuts just to prepopulate the custom time range - which could then modified in details. Do you agree?

As it is now, we cannot accept the PR without getting more PRs/requests. :/

**Comment by godspeed-you** [comment]
I do see the value of a more flexible method to set downtimes. So I close this PR this requires a bigger change in the usability of setting downtimes at all.

**Comment by RevLaw** [comment]
Can you check again, it is still too much work to add this?
I would like an option like "next business day at X o'Clock" or "in X days at X o'Clock"?

There should be a option in this:
image
And there like another field with a Time, so i can choose for example next day at 8 o'Clock.

**Pull request closed without merging**
