### PR TITLE
Update check_sql with SQLAnywhere Support.

### PR DESCRIPTION
**Pull request by TooStrong**
My colleague Andreas Scherer added SQL Anywhere Support to that Plugin.
Can you review, test und put this into next possible Release of CheckMK?
We have testet this successful with SQL Anywhere 17.

Thanks in advance!!!

Kind regards,

Jürgen

Thank you for your interest in contributing to Checkmk!
Unfortunately, due to our current work load, we only consider pure bug fixes as stated in our [Readme](https://github.com/tribe29/checkmk#want-to-contribute).
This means any new pull request that is not a pure bug fix will be closed.
Instead of creating a PR, please consider sharing new check plugins, agent plugins, special agents or notification plugins via the [Checkmk Exchange](https://exchange.checkmk.com/).

## General information

Please give a brief summary of the affected device, software or appliance.
Keep in mind that we are experts in monitoring, but we cannot be experts on all supported devices.
A little context will help us assess your proposed change.

## Bug reports

Please include:

+ Your operating system name and version
+ Any details about your local setup that might be helpful in troubleshooting
+ Detailed steps to reproduce the bug
+ An agent output or SNMP walk
+ The ID of a submitted crash report for reference (if applicable)

## Proposed changes

Sometimes it is hard for us to assess the quality of a fix.
While it may work for you, it is our job to ensure that it works for everybody.
These are some ways to help us:

+ What is the expected behavior?
+ What is the observed behavior?
+ If it's not obvious from the above: In what way does your patch change the current behavior?
+ Consider writing a unit test that would have failed without your fix.
+ Is this a new problem? What made you submit this PR (new firmware, new device, changed device behavior)?

### CODE REVIEW

**Comment by mo-ki** [comment]
Hi Jürgen,
Your change seems to be outdated with respect to the formatting, can you update this? As far as I can tell reading through the noise, this seems to be a compatible extension of the plugins capabilities, but they are not yet configurable via _WATO_, am I right? Can you add that as well?

**Review by mo-ki — APPROVED** [review]

**Comment by TooStrong** [comment]
Hello together,

we had corrected the missing comma in sql.py.
Can you review the changes again, please?

kind regards!

**Comment by mo-ki** [comment]
I'm not sure I understand correctly. AFAICT, the current state only differs by the default port.
I'll add the missing port default in a moment. If there's still something wrong after that, please open a new PR.
Fell free to ping me in the comments if you do!

**Comment by andischerer** [comment]
Everything is fine, it was a misconception by myself. 

I saw this merge request was closed yesterday, so i thought there must be something wrong with it.
I talked to Jürgen(@TooStrong) this morning and we fixed the comma issue(sql.py) from the failing CI-Test in our fork.

Didnt noticed that you are merging MRs "manually" into master in your workflow.

Thanks @mo-ki

**Pull request closed without merging**
