### PR TITLE
Bluenet2 powerrail addition: Sockets and Fuses

### PR DESCRIPTION
**Pull request by gurubert**
This PR adds sockets and fuses monitoring to the check plugin.

It also changes elphase.include to display the "friendly name" that can be set via the PDU administration interface.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Robert,
thank you for this PR. Let's first fix the unit tests. I think the problem is that the character "." is not allowed any more in filenames of checkmans (even if the corresponding check still has it in its name). Could you please replace all "." by a "_" in the filenames of your newly added checkmans?
Best
Jörg

**Comment by jherbel** [comment]
Hi Robert,
we will look at your PR more closely to see if and how we can merge it.
Best
Jörg
Internal reference: CMK-5276

**Comment by gurubert** [comment]
The customer for whom I implemented this patch wants to upgrade to 2.0

Will you merge the changes soon?

bluenet2_powerrail is still a legacy check plugin so this should still be possible.

**Comment by mo-ki** [comment]
Hi Robert,
I'm afraid I will close this PR. We've decided to not add any new plugins to the legacy API, and we're sticking with that.
To be fair, if you implemented this using the new API, my first thought would be to refer you to the exchange and suggest you create an MKP...
I can see that in this case the plugins are very entangled with an existing section, so you would benefit from the code being mainlined, and that an MKP would probably require to much maintenance. Maybe there's a way in the new API to refactor the section into more than one section to untangle them, and come up with a solution that let's you maintain a potential MKP with less effort...
Cheers,
  Moritz

**Pull request closed without merging**
