### PR TITLE
This commit fixes the CMCIII Humidity Checks and sets the Status correctly

### PR DESCRIPTION
**Pull request by OguzhanCicek**
The Status of the Humidity Sensors were not set correctly which resulted in them being in a critical state.
This commit fixes that problem.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi OguzhanCicek,
thank you very much for your PR, it is queued for internal review. Please note that this will take a while, since we are currently very busy with the upcoming release.
Best
Jörg
Internal reference: CMK-5482

**Comment by smokey42** [comment]
We migrated the `cmciii` check to our new Check Plugin API in June 2021. This led to a significant rewrite of the check and testing code.

This may (or may not) have fixed your problem.

If you are still interested, would you please verify that this problem still exists or is resolved with one of our daily builds.

**Comment by mo-ki** [comment]
Hi @OguzhanCicek,
Do you have any updates on this issue? Otherwise we'll close it, and hope that the issue is fixed.

**Comment by si-23** [comment]
Hi @OguzhanCicek,
since we got no more feedback from you we close the PR now.

**Pull request closed without merging**
