### PR TITLE
create labels for docker containers

### PR DESCRIPTION
**Pull request by gurubert**
Docker containers do have an agent data section called "docker_container_labels" which AFAICT is currently no used anywhere.

This check plugin creates host labels from this data section. The labels are prefixed with "docker/".

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Robert, 
thank you for this PR. Before we can look at it more closely, please add a manpage. This should fix one of the two failing unit tests (`test_find_missing_manpages_passive`). The other one will still fail, but that is ok in this case.
Best
Jörg

**Comment by jherbel** [comment]
Hi Robert,
thanks, wee will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.
Internal Ref: CMK-5246

**Comment by gurubert** [comment]
And now I get an error from HW/SW-Inventory in the containers, because the docker_container_labels section was already parsed.

Ergo: There is code in HW/SW-Inventory that uses this section raw, with out parsing it.

**Comment by gurubert** [comment]
WONTFIX :)

**Pull request closed without merging**
