### PR TITLE
ActiveCheck check_mail - Fix message cleanup

### PR DESCRIPTION
**Pull request by Noles**
This fixes the not working message cleanup if check_mail is used with "forward-ec" and "cleanup delete" or "cleanup *folder*"

Without this changes only the following error is shown:
`CRIT - Failed to copy mail: ValueError('not enough values to unpack (expected 2, got 1)')`

Test via CLI:
```bash
OMD[site]:~$ lib/nagios/plugins/check_mail --fetch-protocol=IMAP --fetch-server=*server* --fetch-tls --fetch-username=*username* --fetch-password=*password* --connect-timeout=260 --forward-ec --forward-method= --cleanup *folder* --debug
[b'Logged in']
[b'1']
[b'1']
[(b'1 (RFC822 {1802}', b'Return-Path: ***MASKED***\r\n'), b')']
[b'[COPYUID 1604534060 6492 4912] Copy completed.']
[b'Close completed.']
[b'Logging out']
CRIT - Failed to copy mail: ValueError('not enough values to unpack (expected 2, got 1)'
```

### CODE REVIEW

**Comment by Synss** [comment]
Hi Noles! Thank you for your contribution. Regarding the red CI build, the problem is on our side. You should consider rebasing and trying again.

**Comment by Synss** [comment]
Internal Ref: CMK-6832

**Comment by Noles** [comment]
Hi,
rebased but errors again :-)

**Comment by Noles** [comment]
During test of 2.0.0b3 (CRE) I got an additional error:
`Traceback (most recent call last):
  File "lib/nagios/plugins/check_mail", line 246, in <module>
    active_check_main(create_argument_parser(), check_mail)
  File "/omd/sites/site/lib/python3/cmk/utils/mailbox.py", line 507, in active_check_main
    exitcode, status, perfdata = _active_check_main_core(argument_parser, check_fn, sys.argv[1:])
  File "/omd/sites/site/lib/python3/cmk/utils/mailbox.py", line 455, in _active_check_main_core
    return check_fn(args)
  File "lib/nagios/plugins/check_mail", line 229, in check_mail
    messages, forwarded = prepare_messages_for_ec(
  File "lib/nagios/plugins/check_mail", line 119, in prepare_messages_for_ec
    log_line += '|' + payload[:args.body_limit]
TypeError: can only concatenate str (not "bytes") to str`

As far as I can see this part of code is the same in master branch.

**Comment by UlrichBschorer** [comment]
Hello Alexander,
thanks for your contribution. The next release will contain your improvements.
Kind regards,
Ulrich

**Pull request closed without merging**
