### PR TITLE
Update signl4.py

### PR DESCRIPTION
**Pull request by rons4**
Fix for alert recovery.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Ron,
thank you for this PR, code-wise its fine. I would like to write a small werk for it to document this fix. Would this text be OK?

```
FIX: SIGNL4: status in case of recovery
In case of a recovery, the notification is now shown as resolved.
Otherwise, it is shown as new. This was not the case before.
```

Best
Jörg

**Comment by rons4** [comment]
Hi Jörg,

Thanks and yes, the description is correct.

Also, I have recognized that the notification is marked as failed although the HTTP status code is 201. I will investigate this further.

Thanks and Best Regards

Ron

**Comment by jherbel** [comment]
Ok, but I guess that is is an independent problem, right? So we can still merge this PR, right?

**Comment by rons4** [comment]
Yes, that's independent. Please go ahead and merge this PR. Thanks again ....

**Comment by jherbel** [comment]
I just merged it, the changes will appear on GitHub in a couple of minutes. Thanks again!
Best, Jörg

**Comment by rons4** [comment]
Thanks a lot and have a great weekend ....
Ron

**Pull request closed without merging**
