### PR TITLE
Oracle jobs parameters

### PR DESCRIPTION
**Pull request by Yogibaer75**
The parameter "missingjob" was not set anywhere. Inside the rule the parameter name is "status_missing_jobs".
There is also the possibility to change the WATO parameters to keep the check the same as before.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Andreas,
thank you for this PR. One question: the default value for `status_missing_jobs` in the WATO rule 2. It would be good to have the same default value in the rule and in the check plugin. Do you think it would be OK to change the default value to 2 in the check plugin (the rule is also used in another plugin, `mssql_jobs`)?
Best
Jörg

**Comment by Yogibaer75** [comment]
Hi Jörg,
i think it should be no problem to change the default state to 2. I only kept the old default value. There was no real intention to change it. The problem i only saw as i defined a rule in WATO and it was not respected by the check.

best regards
Andreas

**Comment by jherbel** [comment]
Hi Andreas,
thanks, I just merged this PR.
Best
Jörg

**Comment by moschlar** [comment]
Would it be possible that this fix is also backported to 1.6?

(FWIW: I had reported it some time ago here: https://forum.checkmk.com/t/oracle-jobs-invalid-check-parameter-undefined-key-missingjob-in-the-dictionary/15604)

**Comment by jherbel** [comment]
Hi, I just backported it.
Best, Jörg

**Pull request closed without merging**
