### PR TITLE
De-bash: remove function keyword from shell scripts

### PR DESCRIPTION
**Pull request by rawiriblundell**
The 'function' keyword is a non-portable bashism that is considered deprecated and obsolete.  This PR simply removes it from all identified shell scripts.

### CODE REVIEW

**Comment by jherbel** [comment]
Hello Rawiri,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-5166

**Comment by rawiriblundell** [comment]
Hi,
this is a fairly straightforward change and I'm not sure why it's been sitting here so long.  Extra supporting documentation:

https://wiki.bash-hackers.org/scripting/obsolete
https://wiki.ubuntu.com/DashAsBinSh#function
https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md#function-names

The function keyword will also throw an error in shellcheck if run with a more POSIX strict shell like dash.

Can we please get this merged?

Cheers

**Comment by svenpanne** [comment]
The PR looks sensible to me, could you please upload a squashed version rebased on master? (i.e. a single commit on top of the current master) I have trouble rebasing it...

**Comment by rawiriblundell** [comment]
pylint failure (yet again :) ) aside, this has been done.

**Comment by svenpanne** [comment]
OK, I've fixed the CI failures which we had for some weeks now:

- one missing pylint suppression needed for the raw edition only
- skip tests which rely on OpenSSL 1.1, Travis still runs Xenial

After that, I could cleanly merge your PR. Thanks!

**Pull request closed without merging**
