### PR TITLE
adds Cisco FXOS sensors

### PR DESCRIPTION
**Pull request by thl-cmk**
This PR adds a SNMP Check plugin to monitor the Fan and Power supply sensors of Cisco FXOS (Firepower) appliances.
Temperature is already part of cisco_temperature.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, thank you for this PR, the first thing I need to understand is whether this can clash with `entity_sensors` (the SNMP section and check plugins we looked at in the last PR). Can both be detected at the same time?

**Comment by thl-cmk** [comment]
I don't think so.
 entity_sensors is looking for 
`detect=any_of(
        startswith(OIDSysDescr, "palo alto networks"),
        startswith(OIDSysDescr, "cisco adaptive security appliance"),
    ),`

wehre as this one is checking for:
`    detect=all_of(startswith('.1.3.6.1.2.1.1.1.0', 'Cisco Firepower'),
                  contains('.1.3.6.1.2.1.1.1.0', 'security appliance'),
                  )
`

so sould be exclusive.

**Review by jherbel — CHANGES_REQUESTED** [review]
Ok, since there is no clash with `entity_sensors`, we can use a lot of functionality from there. There is no need to implement your own check plugins, you only need the snmp section, which can be mapped to `entity_sensors` via
`register.snmp_section(..., parsed_section_name="entity_sensors", ...)`
In `parse_cisco_fxos_sensors`, you then need to make sure that you use the same format as `entity_sensors`, i.e., you need 
`def parse_cisco_fxos_sensors(string_table: List[StringTable]) -> EntitySensors:`

**Comment by thl-cmk** [comment]
Hi, thanks for the hint's ;-)

After some playing / thinking, I took a "slightly" broader approach.
I think this check (entity_sensors) can become the base for all the sensor checks
waiting to be moved to the new check API. At the moment there are only 4 or 5 sensor
checks moved and around 200 are waiting. 

Basically I have split the entity_sensors check in 3 parts.

-> the register snmp/parse function: stays in entity_sensors.py
-> the actual checks: moved to generic_sensors.py
-> the helper functions/type definitons: moved to utils/generic_sensors.py

Based on this all the sensor checks will only need a register/parse function.
Everything else is done in the generic_sensors.py check part. With this approach
all migrated checks will have the same look and feel (same WATO options, 
output, perfdata, etc.) And if there improvements to one check, the are available for
all checks of this type (eq. add trend computaion)

Internaly I have moved the Cisco FXOS and Check Point sensor checks to this structure.

Please let me know if we will go this way or how we will proceed. 

btw: I thing in entity_sensors are 2 issues:
-> "Power Sensor" as item name will overlap with real power (consumption) sensors, "Power supply" might be better
-> the defaults lower_levels in entity_sesnsor_fan have precedence over the device state, 
   that means if the sesnor reports OK but the speed is below the defaults the check goes WARN/CRIT

**Comment by jherbel** [comment]
This approach is exactly what I had in mind, but in my opinion, there is no need to rename any files. We can create `cmk/base/plugins/agent_based/utils/entity_sensors.py` for helper functions and type definitions. Other than that, `cmk/base/plugins/agent_based/entity_sensors.py` can stay as it is (probably generic_sensors.py would be a better name, however, there is no need to rename it at the moment).

**Comment by thl-cmk** [comment]
Yes we can do this without renaming, but than we have a unclean structure right at the beginning and for other sesnors we need to change the checks from entity_sensors.py anyway (make them more flexible [for sensors without reading/status], add new sensors like. Power consumtion, Voltage, Humidity....). So if you say we sitll go without renaming, I can do this but I think it's better to start clean right away and don't have to do these changes in the near future.

**Comment by jherbel** [comment]
For now, we leave this as it is. I don't think we have anything unclean here. In case this plugin will become more generic in the future, it can be renamed at this point. However, for now, I like the current name and this PR fits will with it (since we are dealing with CISCO-ENTITY-SENSOR-MIB).

**Comment by thl-cmk** [comment]
OK. Than  I will leave entity_sensors as it is (except for moving some stuff to utils/entity_sensors) but rename te FXOS stuff to cisco_entity_sensors.

**Comment by jherbel** [comment]
Hi, I guess you somehow pushed from the wrong branch or something (239 files changed).

**Comment by thl-cmk** [comment]
Ups. Any hint to resolve this best?

**Comment by jherbel** [comment]
I am not sure how this happened, maybe it was this merge commit 9f37e5d52326d1f753dac59bbc9d51326559f3e1 in your local fork. In general, what you want to do is always _re-base_ your changes onto already merged changes to avoid these merge commits.

I think you could try this:

1. Create a backup branch with your local changes. You do this by simply branching off the branch you want to merge here (`cisco_fxos_sensors`).
2. Update your fork of the checkmk repository: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
3. Reset to `cisco_fxos_sensors` to the current master to (temporarily) remove any modifications you made: https://stackoverflow.com/questions/15432052/what-is-the-meaning-of-git-reset-hard-origin-master/15432250
4. Cherry-pick your actual commits from the backup branch to `cisco_fxos_sensors` and push.

**Pull request closed without merging**
