### PR TITLE
QNAP checks

### PR DESCRIPTION
**Pull request by Ma7h1**
Added New QNAP-Device Checks (Refactored from CMK-Exchange)

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Mathias,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3609

**Comment by anthonyh209** [comment]
Hi Mathias, 

Do you eventually have a SNMP walk for your specific checks? At first glance the propositions look good to me.

**Comment by Ma7h1** [comment]
Hello,

for  sure.

Cheers,
Mathias
[qnap.txt](https://github.com/tribe29/checkmk/files/4198094/qnap.txt)

**Comment by anthonyh209** [comment]
Hi Mathias, 

I wanted to let know you that I have made some changes to your pull request which includes slimming of the temperature check and exclusion of the info check (most aspects here are handled by existing, individual checks such as the uptime check for example). Some additional tests were also added. I then proceeded to merge the resulting files into our master branch under your name. 

The details are listed under Werk 10858.

I hope this is fine with you 

Best, 

Anthony

**Comment by jonaskluger** [comment]
Hello Mathias,

can we assume that you are fine with our changes as mentioned by Anthony? https://github.com/tribe29/checkmk/pull/117#issuecomment-586866660

 
Otherwise we wanted to give you a heads up that we will start closing **stale & inactive** pull request from the end of the week.

Pull request that are pending because more information from the original contributor are needed or pull request that do not follow our contribution guidelines will be affected.

These pull request will be closed after 14 days of inactivity.

This will help us staying up to date with the suggested improvements from the community.
We really appreciate your contribution to our code base! Thank you a lot from the team!

All the best
Jonas

**Comment by Ma7h1** [comment]
Hello Jonas,

I fine with the changes, should I close the pull request ?

Cheers,
Mathias

**Comment by jonaskluger** [comment]
Hey Mathias

thank you for the feedback!

Best
Jonas

**Pull request closed without merging**
