### PR TITLE
Support LVM Cache Pools

### PR DESCRIPTION
**Pull request by gurubert**
With lvmcache(7) it is possible to setup cached LVM volumes, where SSDs speed up slower HDDs.

The current check only supports thin pools, but not cache pools, which throw an error.

This PR implements support for both.
It changes the check parameters to use the filesystem check parameters which are already used by the lvm_vgs check plugin.

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hey Robert, 

thank your for your contribution!
We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Best
Jonas

**Comment by jonaskluger** [comment]
Internal Ref: CMK-2767

**Comment by mo-ki** [comment]
Hi gurubert,
Overall it looks like a good feature, but taking a closer look it just changes too many things at once (not all of those are bad!):
Default levels are changed, the applied ruleset changes (user must set up new rules), item name is changed (user must rediscover), service description changes from "LVM LV Pool Foo" to "LVM LV Foo Pool" (user looses all historic data). Also I strongly object to the use of 'savefloat' and 'saveint'.
I am very sorry to say that I have to close this pull request.

**Comment by gurubert** [comment]
Yes, it is basically a complete new check, but I still think it is worth it.

- the description could be changed back
- default levels are completely different because these checks are now filesystem checks

Why not savefloat or saveint? I have learned in the past that these are the functions from checkmk to use for casting. Are they deprecated? What is the replacement?

**Comment by LarsMichelsen** [comment]
@gurubert: Das sollte ab 1.6.0p4 durch #10321 behoben sein. Danke für den Hinweis.

**Pull request closed without merging**
