### PR TITLE
agent_netapp check. Added --http param, handle -p (--port) param

### PR DESCRIPTION
**Pull request by stmps**
Hey guys! This is the first time I've submitted a pull request on github, so please let me know if I've screwed up. Thanks!

-p and --port were listed as supported parameters, but weren't actually handled anywhere in the code and threw an error if you tried to use them.

Also, in my isolated management environment, we need to force connectivity over HTTP instead of HTTPS.

### CODE REVIEW

**Comment by si-23** [comment]
Hello stmps,

thanks for your patch. The configuration via WATO is missing. Please update your changes.

**Comment by stmps** [comment]
> thanks for your patch. The configuration via WATO is missing. Please update your changes.

Hey Simon!
Just to confirm, are you referring to cmk/gui/plugins/wato/datasource_programs.py ?

**Comment by si-23** [comment]
Hi stmps,

yes, add the conf opts to cmk/gui/plugins/wato/datasource_programs.py.
Please note that the file check_mk/checks/agent_netapp must process these new opts. There the commandline for the netapp agent is created.

**Comment by jonaskluger** [comment]
Closed due to inactivity.

**Pull request closed without merging**
