### PR TITLE
BUG: Kaspersky AV Client - the age is no int but a float.

### PR DESCRIPTION
**Pull request by Yogibaer75**
Also inside the section definition it is shown as float.
!!! This check was not tested after migration to the new Check-API. !!!

Thank you for your interest in contributing to Checkmk!
Unfortunately, due to our current work load, we only consider pure bug fixes as stated in our [Readme](https://github.com/tribe29/checkmk#want-to-contribute).
This means any new pull request that is not a pure bug fix will be closed.
Instead of creating a PR, please consider sharing new check plugins, agent plugins, special agents or notification plugins via the [Checkmk Exchange](https://exchange.checkmk.com/).

## General information

Please give a brief summary of the affected device, software or appliance.
Keep in mind that we are experts in monitoring, but we cannot be experts on all supported devices.
A little context will help us assess your proposed change.

## Bug reports

Please include:

+ Your operating system name and version
+ Any details about your local setup that might be helpful in troubleshooting
+ Detailed steps to reproduce the bug
+ An agent output or SNMP walk
+ The ID of a submitted crash report for reference (if applicable)

## Proposed changes

Sometimes it is hard for us to assess the quality of a fix.
While it may work for you, it is our job to ensure that it works for everybody.
These are some ways to help us:

+ What is the expected behavior?
+ What is the observed behavior?
+ If it's not obvious from the above: In what way does your patch change the current behavior?
+ Consider writing a unit test that would have failed without your fix.
+ Is this a new problem? What made you submit this PR (new firmware, new device, changed device behavior)?

### CODE REVIEW

**Comment by Yogibaer75** [comment]
The job problem has nothing to do with my PR :(

**Comment by kain88-de** [comment]
We had an error on our master branch. That should be fixed now. Can you rebase and run the tests again?

**Comment by Yogibaer75** [comment]
Test is now ok but internally there are really broken things.
Time is defines as an Integer of x seconds. That's clearly wrong.
That's also the reason i cannot change the default parameter to float, as then the testing complains about the WATO rule with again integer seconds and the default parameters with float seconds.

Today a timestamp has normally Micro or Nano seconds. :(

**Comment by mo-ki** [comment]
Hi Andreas,
While the value itself is a float, it should be enough to specify the levels in integer seconds. The check is executed once per minute, so levels with a microsecond resolution don't make much sense (for any *age* of things -- is is different for some sort of latency of course).
I meant to pick your change, but I ended up with a different solution. This will close soonish.
As always: Thank you!

**Comment by Yogibaer75** [comment]
Hallo Moritz,
ich wollte damit nicht sagen, dass Zeit immer ne Fließkomma Zahl sein muss. Das war nur Ausdruck meines Unverständnisses / meiner Abneigung gegenüber den Sinnlosen Tests für Checks. Da diese Tests meist Annahmen treffen welche mit der Wirklichkeit nix zu tun haben. Besser wäre als Grundlage für Check Tests immer ein richtiger Check Output und nicht irgendwelche vorformatierte Variablen/Listen/Dicts. 
Es ist zur Zeit bei einem Commit fast unmöglich diese vorher zu testen da Euer Setup für die lokale Ausführung der Test nicht funktioniert. Das bedeutet ich ändere was, mache den Commit und warte ob der Test auf Github fehlschlägt. Wenn er dies tut ist es echt mühsam zu finden warum, welcher Test genau und warum nicht tut.

Gruß
Andreas

**Pull request closed without merging**
