### PR TITLE
ruleset_matcher: Do not look up labels for irrelevant hosts

### PR DESCRIPTION
**Pull request by jplitza**
In installations with thousands of hosts, this can improve performance notably.

This is a first draft. I guess the new `limit` parameter could (and should) be unified with the `with_foreign_hosts` parameter. But I wanted to get some feedback before restructuring that.

### CODE REVIEW

**Comment by schnetzzz** [comment]
Hi jplitza,
first of all, I'm sorry that you have to dig through this ugly ruleset matching code. It needs a complete overhaul..
The introduced `limit` parameter would more or less nullify the all_matching_hosts mechanism.

```
- cache_id = self._condition_cache_id(hostlist, tags, labels, rule_path), with_foreign_hosts
+ cache_id = self._condition_cache_id(hostlist, tags, labels, rule_path), with_foreign_hosts, limit
```
Adding the `limit` to the cache_id would introduce way more cache entries than before.
This probably has an impact on the memory usage of the check helpers.
On larger installations check_helpers start with a size of 150MB and grow several hundred megabytes, mostly due to caches.
A more specific cache_id very likely increases the growth speed and also the final size of the process.

Any changes in the ruleset matching code are obviously quite dangerous. We can not integrate this into Version 1.6 or 2.0.
For the upcoming version 2.1 there might be room for something new.

Last year, I've already written a prototype with an alternative rule matching mechanism.
It showed promising results, but I didn't have the time to finish it.

- Scrap the old rule matching
- Determine all existing tags, create a bitmask for them
- Generate the tag bitmask for each host/service
- For rules generate
-- A bitmask that must match
-- A bitmask that must not match
-- A list of bitmasks where one bitmask must match
-- probably some further special handlings

Comparing the bitmasks is way faster than doing the string comparison for each tag over and over again.
Hopefully I will have the time to finish it in version 2.1.

Regards
Andreas

**Comment by jplitza** [comment]
@schnetzzz Thanks for the reply!

I'm assuming that "check_helpers" refers to the CEE feature of checkers and fetchers? I'm using CRE, and my understanding is that there, one Python check process is started per host, so each process only ever reads rulesets for this one host. So cache size shouldn't change, at least in these check processes. (Originally, I didn't cache these limited ruleset results at all.)

Conversely, reading the labels for all hosts in each of these processes is a huge waste if resources. At that would also be necessary for your bitmap approach, wouldn't it?

**Comment by schnetzzz** [comment]
CRE, good point!
In the CEE the check_helpers are always active and consume lots of memory.

The CRE uses a different approach. Each CheckMK check starts a python script specifically designed for this host.
Your change would indeed speed up the startup phase for the CheckMK check.

However, another question. Why are the other hosts here known at all?
There is no need to speed up the rule matching, if we can prevent the number of hosts known to this script.

**Comment by jplitza** [comment]
> However, another question. Why are the other hosts here known at all?

Well, I'm not deep enough into the Check_MK architecture to answer that. 😉

> There is no need to speed up the rule matching, if we can prevent the number of hosts known to this script.

Sure. I just noticed via strace that the check processes spend a lot of time opening and reading the label files for all hosts.

**Comment by schnetzzz** [comment]
Right, it doesn't make very much sense to iterate through all hosts. Maybe through relevant clusters for this host.
I'm going to create an internal Jira Ticket for these new insight. We will have a look at it later on.

Thanks!

**Comment by jplitza** [comment]
@schnetzzz Any chance I can "subscribe" to that Jira Ticket? I'll gladly test your implementation. And once its merged, I can stop merging my patch on every update.

**Pull request closed without merging**
