### PR TITLE
Add Fortinet Sandbox System Check

### PR DESCRIPTION
**Pull request by spenneb**
This pull request adds a system firmware version check for the Fortinet Sandbox Appliance

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Ralf,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3462

**Comment by marcelcaspar** [comment]
Here applies the same as in https://github.com/tribe29/checkmk/pull/100#issuecomment-587004637.
An inventory plugin would be a better fit for version information.

You could also easily combine this with the other pull request into a single inventory plugin that queries the snmp info of the firmware version as well as the version of other installed software.

**Comment by Teimel** [comment]
Hello Ralf,

as per marcelcaspar's comment, an inventory plugin is better suited in this case (static state is returned + firmware version). Let us know if you want to proceed on this pull request or we should close it.

Regards
Timi

**Comment by TimotheusBachinger** [comment]
Closing:
    Notice: this issue has been closed because it has been inactive for > 30 days.
    You may reopen this issue if it has been closed in error.

Internal Ref: CMK-3462

**Pull request closed without merging**
