### PR TITLE
Integration of checkmk with Freshservice API.

### PR DESCRIPTION
**Pull request by Sasidharan3094**
Integration of checkmk with freshservice API.
Freshervice API Documentation - https://api.freshservice.com/v2/

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, t
hank you for this PR. Before we can look at it more closely, all the tests need to work. Here, you can find more information:
https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md#how-to-execute-tests
Best
Jörg

**Comment by Sasidharan3094** [comment]
@jherbel Requesting you to delete this PR as i had pasted one of our API URL in the code. I will raise new PR and will submit as per required. [Here, you can find more information:
https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md#how-to-execute-tests]

Thanks in advance.

**Comment by jherbel** [comment]
Hi @Sasidharan3094, unfortunately, there is no way for us to delete PRs. As far as I know, the only way is to ask the GitHub support to delete it. If you want to do that, it would of course be totally fine from our side.

**Comment by Sasidharan3094** [comment]
Hi @jherbel, I already reached out to Github support, and please find below from the Github support team.
So, requesting you to delete the PR by contacting them. Thanks in advance!

"For privacy and security reasons, only an admin of that repository can request that we delete this pull request. If you're able to get in touch with an admin directly, the quickest way to resolve this would be for them to write in requesting that we delete the pull request. They can reach out to us directly, or in a reply to this email if you'd like to CC them."

**Comment by jherbel** [comment]
Hi @LarsMichelsen, could you please get in touch the GitHub support in order to delete this PR? The reason is that by mistake, one of the commits contains a URL which should not have been made public. This is the URL where you can contact the GitHub support: 
https://support.github.com/request
I guess the topic would be "Remove data from a repository I own or control". Thank you!

**Comment by svenpanne** [comment]
Does a force push help? Or will the original change still be visible? And is it just about the API URL?

**Comment by LarsMichelsen** [comment]
Just sent the request to GitHub support.

**Pull request closed without merging**
