### PR TITLE
add auth mechanism X509 for mongodb

### PR DESCRIPTION
**Pull request by elwood218**
Thank you for your interest in contributing to Checkmk!
Unfortunately, due to our current work load, we only consider pure bug fixes as stated in our [Readme](https://github.com/tribe29/checkmk#want-to-contribute).
This means any new pull request that is not a pure bug fix will be closed.
Instead of creating a PR, please consider sharing new check plugins, agent plugins, special agents or notification plugins via the [Checkmk Exchange](https://exchange.checkmk.com/).

## General information

The mongodb plugin need X509 (certificate) auth mechanism. If a mongodb cluster got SSL enabled there is a need for having that - otherwise it cannot be accessed.

## Bug reports

...

## Proposed changes

This change will adjust the plugin mk_mongodb.py and an example config which will allow auth mechanism X509.
TBD: Integrate those options in Checkmk GUI. Didn't find yet, maybe you can give me a hint.

### CODE REVIEW

**Comment by elwood218** [comment]
@kain88-de I have fixed the issues mentioned by the unit-tests. Is there something else I have to do? Could you also please give me a hint where to find the code for putting the new options to the GUI extension?
Thank you :)

**Comment by elwood218** [comment]
@kain88-de Could you please explain what this test means? I don't know what this failed error message shall tell me..

**Comment by mo-ki** [comment]
> Could you also please give me a hint where to find the code for putting the new options to the GUI extension?

You can't find it on this repo, as it is enterprise-only code. In an installed 2.1 CEE, you can find the files at `lib/check_mk/gui/cee/plugins/wato/agent_bakery/rulespecs/mk_mongodb.py` and `lib/check_mk/base/cee/plugins/bakery/mk_mongodb.py`.

We are currently working on the GUI integration, such that we can merge this.

**Comment by elwood218** [comment]
Great! Thank you! :)

**Comment by elwood218** [comment]
Hello.. what is the status here? We don't get your updates to the plugin as long x509 auth is not included !

**Comment by racicLuka** [comment]
Hello, sorry for the late answer. I haven't been able to answer earlier. We are working on the change and it  will be merged during the current sprint (until March 21st).
Once again, sorry for the late response and thanks for the understanding!

**Comment by racicLuka** [comment]
The change is merged and available in master now. Sorry for the wait and thank you for you contribution and help!

**Pull request closed without merging**
