### PR TITLE
AIX Inventory: Use more info about physical volumes and network from prtconf

### PR DESCRIPTION
**Pull request by MarkusGaelli**
**AIX Inventory Extension: Process more data from prtconf**

The current "prtconf" parser states in a comment:
```
# Note: this is only the header. Much more stuff follows, but is currently
# not being parsed.
```
This extension helps to process more data from "prtconf", namely the following:
- Parse and display information about physical volume groups and their volumes ("name", "partitions", "status"):
prtconf_physical_volumes
- Parse and display information about the network configuration ("domain name", "ip address", "gateway", "netmask", "name_server")
prt-conf-network

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hello Markus,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4107

**Comment by MarkusGaelli** [comment]
> Hello Markus,
> 
> thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.
> 
> Internal Ref: CMK-4107

Hi Jonas, All

Any news / ETAs on that?
 Thx

Markus

**Comment by jonaskluger** [comment]
Hey Markus,

this PR is currently in progress on our end and a college is having a closer look at the moment.

Best
Jonas

**Comment by anthonyh209** [comment]
Hi @MarkusGaelli,
thanks for your input. I had a look through your suggested changes and it generally looks good to me. I would like to test your suggestions on some of our test sites. Could you eventually attach a sample AIX output file (for the prtconf inventory plugin) to your commit?

Thanks

**Comment by MarkusGaelli** [comment]
Hi Anthony

Just added a few more lines to the prtconf file where you should find the important sections. Had a small issue with the .gitignore, hope this is fine now?

Cheers
Markus

**Comment by MarkusGaelli** [comment]
Hi

Added better sample to the prtconf file in inventory. Ok?

Cheers
Markus

**Comment by anthonyh209** [comment]
Hi Markus, 
the output helped a lot. Thank you According to the

**Comment by anthonyh209** [comment]
Hi Markus, 
I have merged the changes into our master branch. As previously mentioned, I have made some further changes regarding the implementation. Thanks again for the suggestions

**Comment by MarkusGaelli** [comment]
Jonas, Anthony: Many thanks to you !

Best regards
Markus

**Pull request closed without merging**
