### PR TITLE
Added storcli check for linux

### PR DESCRIPTION
**Pull request by MrCamby**
Check based on the already existing windows check

### CODE REVIEW

**Comment by jonaskluger** [comment]
Hey Jan,

please make sure that the all tests are okay, so we can proceed with your pull request.

Best
Jonas

**Comment by MrCamby** [comment]
Heay @jonaskluger,

I don´t know if you did received a message about the successful checks.
So just a quick reminder :)

**Comment by LarsMichelsen** [comment]
We received the update, thanks for that. We'll need some more time to check this change.

**Comment by n00rm** [comment]
Please consider that the file paths of the stor cli are not consitent. 
When you use the LSI Storcli, the installation path is /opt/lsi/storcli (also used in the vmware vib)
In this pull request only the Mega Raid storcli path is used. (/opt/MegaRAID/storcli/storcli64)

**Comment by jonaskluger** [comment]
Hello Jan,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3937

**Comment by jcpunk** [comment]
I'll confess some interest in this myself....

**Comment by Taker567** [comment]
Also very interested in this feature.

**Comment by m4c3** [comment]
Whats the benefit of storecli over megacli?
cause megacli is already native in the linux agent..

**Comment by jcpunk** [comment]
As I understand it StorCLI is the successor of the MegaCLI command.

**Comment by m4c3** [comment]
i looked into the linux agent for the megacli section and i was surprised that the storcli is already in there https://github.com/tribe29/checkmk/blob/ee43964342401c2be704e20c74466fc6f0da6b8d/agents/check_mk_agent.linux#L533-L536
wouldn't it be better to refactor the megacli section in the agent to adapt the different storcli subcommands?

**Comment by rawiriblundell** [comment]
The above comments indicates that there's a bug.  Here's some untested code to fix it, derived from code I wrote a couple of years ago.  Will likely require a `PATH` test-and-append like `qmail` i.e.

```
[ -d /opt/MegaRAID/storcli/ ] && PATH=${PATH}:/opt/MegaRAID/storcli
```

I'll leave it to someone else to figure out how/where to plumb this in - should this be deemed as worthy of inclusion.

```
# Find megacli and setup a helper function for section_megacli()
for _cli_opt in MegaCli MegaCli64 megacli; do
    if inpath "${_cli_opt}"; then
        # Possible TO-DO: validate that this isn't a symlink to storcli
        get_megacli() { "${_cli_opt}"; }
        unset -v _cli_opt
        break
    fi
    unset -v _cli_opt
done

# Find storcli and setup a helper function for section_storcli()
for _cli_opt in storcli storcli64; do
    if inpath "${_cli_opt}"; then
        get_storcli() { "${_cli_opt}"; }
        unset -v _cli_opt
        break
    fi
    unset -v _cli_opt
done

section_storcli() {
    # If our helper function isn't defined, then bounce out of this function
    inpath get_storcli || return

    # These commands can be appended with "J" to output JSON
    # e.g. get_storcli /call/eall/sall show J
    printf -- '%s\n' "<<<storcli_pdisks>>>"
    get_storcli /call/eall/sall show

    printf -- '%s\n' "<<<storcli_vdrives>>>"
    get_storcli /call/vall show

    printf -- '%s\n' "<<<storcli_bbu>>>"
    get_storcli /call/bbu show status
}

section_megacli() {
    # If our helper function isn't defined, then bounce out of this function
    inpath get_megacli || return

    # When storcli and megacli are both present, megacli is often a symlink to storcli
    # We check for storcli first and bounce out if we find it (i.e. section_storcli() is doing the work)
    inpath storcli && return
    inpath storcli64 && return

    # Define the physical disk information we want to grep out
    _pdfilter='Enclosure|Raw Size|Slot Number|Device Id|Firmware state|Inquiry|Adapter|Predictive Failure Count'

    # Physical
    printf -- '%s\n' '<<<megaraid_pdisks>>>'
    for part in $(get_megacli -EncInfo -aALL -NoLog </dev/null |
        sed -rn 's/:/ /g; s/[[:space:]]+/ /g; s/^ //; s/ $//; s/Number of enclosures on adapter ([0-9]+).*/adapter \1/g; /^(Enclosure|Device ID|adapter) [0-9]+$/ p'); do
        [ "$part" = adapter ] && printf -- '%s\n' ""
        # shellcheck disable=SC2039
        [ "$part" = 'Enclosure' ] && printf -- '\n%s\n' "dev2enc"
        # shellcheck disable=SC2039
        printf -- '%s' " $part"
    done
    printf -- '%s\n' ""
    get_megacli -PDList -aALL -NoLog </dev/null | grep -E "${_pdfilter}"

    # Virtual drives
    printf -- '%s\n' '<<<megaraid_ldisks>>>'
    get_megacli -LDInfo -Lall -aALL -NoLog </dev/null | grep -E 'Size|State|Number|Adapter|Virtual'

    # Battery status
    printf -- '%s\n' '<<<megaraid_bbu>>>'
    get_megacli -AdpBbuCmd -GetBbuStatus -aALL -NoLog </dev/null | grep -v Exit
    
    unset -v _pdfilter part
}
```

It would be useful if someone reading this could provide some example outputs for the following commands:

```
storcli /call/eall/sall show
storcli /call/vall show
storcli /call/bbu show status
```

**Comment by jcpunk** [comment]
```shell
[root@example-host ~]# storcli /call/eall/sall show
CLI Version = 007.0813.0000.0000 Dec 14, 2018
Operating system = Linux 2.6.32-754.30.2.el6.x86_64
Controller = 0
Status = Success
Description = Show Drive Information Succeeded.


Drive Information :
=================

--------------------------------------------------------------------------------
EID:Slt DID State DG     Size Intf Med SED PI SeSz Model                Sp Type 
--------------------------------------------------------------------------------
32:0     30 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:1     26 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:2     28 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:3     35 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:4     37 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:5     43 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:6     44 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:7     25 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:8     24 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:9     39 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:10    33 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:11    34 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:12    47 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:13    40 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:14    23 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:15    42 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:16    29 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:17    22 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:18    45 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:19    27 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:20    36 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:21    41 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:22    31 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
32:23    38 Onln   1 3.637 TB SAS  HDD N   N  512B HUS726040AL5210      U  -    
46:13    48 GHS    - 3.637 TB SATA HDD N   N  512B HGST HUS726040ALA610 D  -    
252:0    20 Onln   0 931.0 GB SATA HDD N   N  512B HGST HUS722T1TALA604 U  -    
252:1    21 Onln   0 931.0 GB SATA HDD N   N  512B HGST HUS722T1TALA604 U  -    
--------------------------------------------------------------------------------

EID-Enclosure Device ID|Slt-Slot No.|DID-Device ID|DG-DriveGroup
DHS-Dedicated Hot Spare|UGood-Unconfigured Good|GHS-Global Hotspare
UBad-Unconfigured Bad|Onln-Online|Offln-Offline|Intf-Interface
Med-Media Type|SED-Self Encryptive Drive|PI-Protection Info
SeSz-Sector Size|Sp-Spun|U-Up|D-Down/PowerSave|T-Transition|F-Foreign
UGUnsp-Unsupported|UGShld-UnConfigured shielded|HSPShld-Hotspare shielded
CFShld-Configured shielded|Cpybck-CopyBack|CBShld-Copyback Shielded



[root@example-host ~]# storcli /call/vall show
CLI Version = 007.0813.0000.0000 Dec 14, 2018
Operating system = Linux 2.6.32-754.30.2.el6.x86_64
Controller = 0
Status = Success
Description = None


Virtual Drives :
==============

---------------------------------------------------------------
DG/VD TYPE   State Access Consist Cache Cac sCC      Size Name 
---------------------------------------------------------------
0/0   RAID1  Optl  RW     Yes     RAWBC -   ON   931.0 GB OS   
1/1   RAID10 Optl  RW     Yes     RAWBC -   ON  43.658 TB DATA 
---------------------------------------------------------------

Cac=CacheCade|Rec=Recovery|OfLn=OffLine|Pdgd=Partially Degraded|Dgrd=Degraded
Optl=Optimal|RO=Read Only|RW=Read Write|HD=Hidden|TRANS=TransportReady|B=Blocked|
Consist=Consistent|R=Read Ahead Always|NR=No Read Ahead|WB=WriteBack|
AWB=Always WriteBack|WT=WriteThrough|C=Cached IO|D=Direct IO|sCC=Scheduled
Check Consistency



[root@example-host ~]# storcli /call/bbu show status
CLI Version = 007.0813.0000.0000 Dec 14, 2018
Operating system = Linux 2.6.32-754.30.2.el6.x86_64
Controller = 0
Status = Failure
Description = None

Detailed Status :
===============

--------------------------------------
Ctrl Status Property ErrMsg     ErrCd 
--------------------------------------
   0 Failed -        use /cx/cv   255 
--------------------------------------
```

**Comment by motherboard1999** [comment]
@LarsMichelsen @jonaskluger Any updates about the StorCLI check for Linux? At the moment we cant monitor our RAID because "newer" cards dont work with MegaCLI. This is a essential feature of a paid monitoring system!

**Comment by mo-ki** [comment]
I am currently working on it. Apart from my time, the limiting factor is my lack of access to such RAIDS. 
@motherboard1999 : If you choose to open a support ticket, make sure to mention my name, and the fact that you known I am working on it.

**Comment by motherboard1999** [comment]
> I am currently working on it. Apart from my time, the limiting factor is my lack of access to such RAIDS. @motherboard1999 : If you choose to open a support ticket, make sure to mention my name, and the fact that you known I am working on it.

If you need some command output or something, just let me know

**Comment by mo-ki** [comment]
I'll take you up on that :-)

It seems like `/bbu` is gone, it's `/cv` now. Would you share the output of `storcli /call/cv show all`?
I am currently baffled by the inconsistency of the plugins `megaraid_pdisks` and `storcli_pdisks` ...

It seems to me that monitoring the "Predictive fail count" is probably more important than the size (the latter should go to the **ha**rdware/**s**oftware **i**nventory, I think). That would mean we'd have to use `/call /eall /sall show all` (of which I have an output).

**Comment by michaelfuckner** [comment]
[20:06:28][root@hydra:~]$ /usr/local/bin/storcli /c0/cv show all
CLI Version = 007.0709.0000.0000 Aug 14, 2018
Operating system = Linux 5.10.0-8-amd64
Controller = 0
Status = Success
Description = None


Cachevault_Info :
===============

--------------------
Property    Value
--------------------
Type        CVPM02
Temperature 42 C
State       Optimal
--------------------


Firmware_Status :
===============

---------------------------------------
Property                         Value
---------------------------------------
NVCache State                    OK
Replacement required             No
No space to cache offload        No
Module microcode update required No
---------------------------------------


GasGaugeStatus :
==============

------------------------------
Property                Value
------------------------------
Pack Energy             254 J
Capacitance             113 %
Remaining Reserve Space 0
------------------------------


Design_Info :
===========

------------------------------------
Property                 Value
------------------------------------
Date of Manufacture      15/10/2019
Serial Number            19408
Manufacture Name         LSI
Design Capacity          288 J
Device Name              CVPM02
tmmFru                   N/A
CacheVault Flash Size    4.0 GB
tmmBatversionNo          0x01
tmmSerialNo              0x1d22
tmm Date of Manufacture  09/03/2021
tmmPcbAssmNo             0225444231
tmmPCBversionNo          0x02
tmmBatPackAssmNo         49571-15C
scapBatversionNo         0x00
scapSerialNo             0x4bd0
scap Date of Manufacture 15/10/2019
scapPcbAssmNo            1700154483
scapPCBversionNo          E
scapBatPackAssmNo        49571-15C
Module Version           6071-04A
------------------------------------


Properties :
==========

--------------------------------------------------------------
Property             Value
--------------------------------------------------------------
Auto Learn Period    27d (2412000 seconds)
Next Learn time      2022/05/19  10:50:12 (706272612 seconds)
Learn Delay Interval 0 hour(s)
Auto-Learn Mode      Transparent
--------------------------------------------------------------



[20:06:54][root@hydra:~]$

**Comment by jcpunk** [comment]
I believe `storcli` also has a `JSON` output mode if that would be easier to parse server side.

**Comment by michaelfuckner** [comment]
[22:17:16][root@hydra:~]$ /usr/local/bin/storcli /c0/cv show all J
{
"Controllers":[
{
        "Command Status" : {
                "CLI Version" : "007.0709.0000.0000 Aug 14, 2018",
                "Operating system" : "Linux 5.10.0-8-amd64",
                "Controller" : 0,
                "Status" : "Success",
                "Description" : "None"
        },
        "Response Data" : {
                "Cachevault_Info" : [
                        {
                                "Property" : "Type",
                                "Value" : "CVPM02"
                        },
                        {
                                "Property" : "Temperature",
                                "Value" : "41 C"
                        },
                        {
                                "Property" : "State",
                                "Value" : "Optimal"
                        }
                ],
                "Firmware_Status" : [
                        {
                                "Property" : "NVCache State",
                                "Value" : "OK"
                        },
                        {
                                "Property" : "Replacement required",
                                "Value" : "No"
                        },
                        {
                                "Property" : "No space to cache offload",
                                "Value" : "No"
                        },
                        {
                                "Property" : "Module microcode update required",
                                "Value" : "No"
                        }
                ],
                "GasGaugeStatus" : [
                        {
                                "Property" : "Pack Energy",
                                "Value" : "254 J"
                        },
                        {
                                "Property" : "Capacitance",
                                "Value" : "113 %"
                        },
                        {
                                "Property" : "Remaining Reserve Space",
                                "Value" : 0
                        }
                ],
                "Design_Info" : [
                        {
                                "Property" : "Date of Manufacture",
                                "Value" : "15/10/2019"
                        },
                        {
                                "Property" : "Serial Number",
                                "Value" : 19408
                        },
                        {
                                "Property" : "Manufacture Name",
                                "Value" : "LSI"
                        },
                        {
                                "Property" : "Design Capacity",
                                "Value" : "288 J"
                        },
                        {
                                "Property" : "Device Name",
                                "Value" : "CVPM02"
                        },
                        {
                                "Property" : "tmmFru",
                                "Value" : "N/A"
                        },
                        {
                                "Property" : "CacheVault Flash Size",
                                "Value" : "4.0 GB"
                        },
                        {
                                "Property" : "tmmBatversionNo",
                                "Value" : "0x01"
                        },
                        {
                                "Property" : "tmmSerialNo",
                                "Value" : "0x1d22"
                        },
                        {
                                "Property" : "tmm Date of Manufacture",
                                "Value" : "09/03/2021"
                        },
                        {
                                "Property" : "tmmPcbAssmNo",
                                "Value" : "0225444231"
                        },
                        {
                                "Property" : "tmmPCBversionNo",
                                "Value" : "0x02"
                        },
                        {
                                "Property" : "tmmBatPackAssmNo",
                                "Value" : "49571-15C"
                        },
                        {
                                "Property" : "scapBatversionNo",
                                "Value" : "0x00"
                        },
                        {
                                "Property" : "scapSerialNo",
                                "Value" : "0x4bd0"
                        },
                        {
                                "Property" : "scap Date of Manufacture",
                                "Value" : "15/10/2019"
                        },
                        {
                                "Property" : "scapPcbAssmNo",
                                "Value" : "1700154483"
                        },
                        {
                                "Property" : "scapPCBversionNo",
                                "Value" : " E"
                        },
                        {
                                "Property" : "scapBatPackAssmNo",
                                "Value" : "49571-15C"
                        },
                        {
                                "Property" : "Module Version",
                                "Value" : "6071-04A"
                        }
                ],
                "Properties" : [
                        {
                                "Property" : "Auto Learn Period",
                                "Value" : "27d (2412000 seconds)"
                        },
                        {
                                "Property" : "Next Learn time",
                                "Value" : "2022/05/19  10:50:12 (706272612 seconds)"
                        },
                        {
                                "Property" : "Learn Delay Interval",
                                "Value" : "0 hour(s)"
                        },
                        {
                                "Property" : "Auto-Learn Mode",
                                "Value" : "Transparent"
                        }
                ]
        }
}
]
}

**Comment by mo-ki** [comment]
Unfortunately the `J` is ignored on Windows, so I'll have to deal with the non-json output anyway :-(
Michael, thank you so much for helping me out! Can I ask you to post the output of the "/call/vc show all" (ideally /c*all*, not /c0) as code (between to lines containing only ` ``` ` )? Github rendereing this as markdown is entertaining, but makes it unusable for me...

**Comment by michaelfuckner** [comment]
```
[17:05:13][root@hydra:~]$ /usr/local/bin/storcli /c0/cv show all J
{
"Controllers":[
{
	"Command Status" : {
		"CLI Version" : "007.0709.0000.0000 Aug 14, 2018",
		"Operating system" : "Linux 5.10.0-8-amd64",
		"Controller" : 0,
		"Status" : "Success",
		"Description" : "None"
	},
	"Response Data" : {
		"Cachevault_Info" : [
			{
				"Property" : "Type",
				"Value" : "CVPM02"
			},
			{
				"Property" : "Temperature",
				"Value" : "39 C"
			},
			{
				"Property" : "State",
				"Value" : "Optimal"
			}
		],
		"Firmware_Status" : [
			{
				"Property" : "NVCache State",
				"Value" : "OK"
			},
			{
				"Property" : "Replacement required",
				"Value" : "No"
			},
			{
				"Property" : "No space to cache offload",
				"Value" : "No"
			},
			{
				"Property" : "Module microcode update required",
				"Value" : "No"
			}
		],
		"GasGaugeStatus" : [
			{
				"Property" : "Pack Energy",
				"Value" : "254 J"
			},
			{
				"Property" : "Capacitance",
				"Value" : "113 %"
			},
			{
				"Property" : "Remaining Reserve Space",
				"Value" : 0
			}
		],
		"Design_Info" : [
			{
				"Property" : "Date of Manufacture",
				"Value" : "15/10/2019"
			},
			{
				"Property" : "Serial Number",
				"Value" : 19408
			},
			{
				"Property" : "Manufacture Name",
				"Value" : "LSI"
			},
			{
				"Property" : "Design Capacity",
				"Value" : "288 J"
			},
			{
				"Property" : "Device Name",
				"Value" : "CVPM02"
			},
			{
				"Property" : "tmmFru",
				"Value" : "N/A"
			},
			{
				"Property" : "CacheVault Flash Size",
				"Value" : "4.0 GB"
			},
			{
				"Property" : "tmmBatversionNo",
				"Value" : "0x01"
			},
			{
				"Property" : "tmmSerialNo",
				"Value" : "0x1d22"
			},
			{
				"Property" : "tmm Date of Manufacture",
				"Value" : "09/03/2021"
			},
			{
				"Property" : "tmmPcbAssmNo",
				"Value" : "0225444231"
			},
			{
				"Property" : "tmmPCBversionNo",
				"Value" : "0x02"
			},
			{
				"Property" : "tmmBatPackAssmNo",
				"Value" : "49571-15C"
			},
			{
				"Property" : "scapBatversionNo",
				"Value" : "0x00"
			},
			{
				"Property" : "scapSerialNo",
				"Value" : "0x4bd0"
			},
			{
				"Property" : "scap Date of Manufacture",
				"Value" : "15/10/2019"
			},
			{
				"Property" : "scapPcbAssmNo",
				"Value" : "1700154483"
			},
			{
				"Property" : "scapPCBversionNo",
				"Value" : " E"
			},
			{
				"Property" : "scapBatPackAssmNo",
				"Value" : "49571-15C"
			},
			{
				"Property" : "Module Version",
				"Value" : "6071-04A"
			}
		],
		"Properties" : [
			{
				"Property" : "Auto Learn Period",
				"Value" : "27d (2412000 seconds)"
			},
			{
				"Property" : "Next Learn time",
				"Value" : "2022/05/19  10:50:12 (706272612 seconds)"
			},
			{
				"Property" : "Learn Delay Interval",
				"Value" : "0 hour(s)"
			},
			{
				"Property" : "Auto-Learn Mode",
				"Value" : "Transparent"
			}
		]
	}
}
]
}
```

**Comment by jcpunk** [comment]
From the `storcli` manual:

> JSON format output is not supported in the EFI operating system . The EFI platform ignores the J when it is added at the end of the command syntax.

That is an odd constraint, but I suspect it is relevant.

**Comment by motherboard1999** [comment]
[14:09:17][root@hydra:~]$ storcli /call/vc show all
```
syntax error, unexpected TOKEN_UNKNOWN

     Storage Command Line Tool  Ver 007.0709.0000.0000 Aug 14, 2018

     (c)Copyright 2018, AVAGO Technologies, All Rights Reserved.
...
```

[14:10:38][root@hydra:~]$ storcli /call/cv show all
```CLI Version = 007.0709.0000.0000 Aug 14, 2018
Operating system = Linux 5.10.0-8-amd64
Controller = 0
Status = Success
Description = None


Cachevault_Info :
===============

--------------------
Property    Value
--------------------
Type        CVPM02
Temperature 38 C
State       Optimal
--------------------


Firmware_Status :
===============

---------------------------------------
Property                         Value
---------------------------------------
NVCache State                    OK
Replacement required             No
No space to cache offload        No
Module microcode update required No
---------------------------------------


GasGaugeStatus :
==============

------------------------------
Property                Value
------------------------------
Pack Energy             254 J
Capacitance             113 %
Remaining Reserve Space 0
------------------------------


Design_Info :
===========

------------------------------------
Property                 Value
------------------------------------
Date of Manufacture      15/10/2019
Serial Number            19408
Manufacture Name         LSI
Design Capacity          288 J
Device Name              CVPM02
tmmFru                   N/A
CacheVault Flash Size    4.0 GB
tmmBatversionNo          0x01
tmmSerialNo              0x1d22
tmm Date of Manufacture  09/03/2021
tmmPcbAssmNo             0225444231
tmmPCBversionNo          0x02
tmmBatPackAssmNo         49571-15C
scapBatversionNo         0x00
scapSerialNo             0x4bd0
scap Date of Manufacture 15/10/2019
scapPcbAssmNo            1700154483
scapPCBversionNo          E
scapBatPackAssmNo        49571-15C
Module Version           6071-04A
------------------------------------


Properties :
==========

--------------------------------------------------------------
Property             Value
--------------------------------------------------------------
Auto Learn Period    27d (2412000 seconds)
Next Learn time      2022/05/19  10:50:12 (706272612 seconds)
Learn Delay Interval 0 hour(s)
Auto-Learn Mode      Transparent
--------------------------------------------------------------```

**Comment by mo-ki** [comment]
Hi everybody, just a quick heads up: The plugins for the physical and logical/virtual disks are almost done, I will merge that soonish. That commit will close this PR.
I not sure whether there will be a 'cache vault' plugin; I'm not fully confident how to deal with the output corresponding to multiple controllers, i.e. how the output of "/call" and "/c0" differ. It seems to  me they are identical, if only one controller is connected.
I will continue the discussion in the Checkmk Forum, since there is a thread regarding this issue anyway: https://forum.checkmk.com/t/lsi-megaraid-controller-check-has-deprecated-commands/25966

Thank you all very much for the provided output!

**Comment by jcpunk** [comment]
Will this patch be available for the 2.0 series?

**Comment by mo-ki** [comment]
Sorry @jcpunk, this is to big to backport it to the 2.0. However: If you add all affected/new files to an MKP (and add some empty files to overwrite the `checks/` files that the commit removes) it should work in principle.

**Pull request closed without merging**
