### PR TITLE
Move 'then' and 'do' to same line as per style guide

### PR DESCRIPTION
**Pull request by rawiriblundell**
Hi,
first simplified pull request.  This one simply moves 'then' and 'do' to be the same line as the loop declaration, as per the Google Style Guide:

https://google.github.io/styleguide/shell.xml#Loops

Note: I have only applied this change to the Linux agent.  Others are free to apply the same change to the other agents.  You're looking for things like:

\n^then$
\n^do$
\n\s+then$
\n\s+do$

Rawiri

### CODE REVIEW

**Comment by gurubert** [comment]
Your commit contains the changes from https://github.com/tribe29/checkmk/pull/4 (by accident?)

**Comment by rawiriblundell** [comment]
> Your commit contains the changes from #4 (by accident?)

Hi gurubert,
"kinda".  In anticipation of your pull request being accepted and merged (because it seems like a straightforward change to me), I added it to my fork and updated it.  You'll note that I make a couple of style adjustments, as well as replacing your 'ls|cut' call with 'stat'.

I didn't mean for that commit to show up in this pull request, but it is what it is.

Cheers

Rawiri

**Comment by 7omb** [comment]
Hi Rawiri,
can you exclude the changes for #4? The ps section will take some more time, but I'd like to merge this PR.

**Comment by rawiriblundell** [comment]
Hi 7omb,
done. :)

Rawiri

**Pull request closed without merging**
