### PR TITLE
Fortinet FortiMail System load Check

### PR DESCRIPTION
**Pull request by OguzhanCicek**
This PR adds a SNMP check for Fortinet FortiMail Systems
to check the system load

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, one question about fmlSysLoad: I guess this number is a percentage between 0 and 100, right? So even though it is called load, it seems more like a utilization to me and has nothing to do with a CPU load. Would you agree?

**Comment by OguzhanCicek** [comment]
I was under the assumption that the SystemLoad is meant to be the cpu utilization since that snmp walks i used always had big even numbers. The MIB does also specify fmlSysCpuUsage which means that fmlSysLoad is the system load. I changed the unit definition, removed the "%" and replaced the thresholds from 90%/95% to 5/15.

**Comment by jherbel** [comment]
Hmm, since we are indeed talking about load, sensible levels depend on the number of CPUs. How many CPUs do these system have?

**Comment by OguzhanCicek** [comment]
the fortimail MIB does not specify a way of getting the amount of CPUs but with the help of the datasheet and some snmpwalks i think i found a way of getting it. It turns out that i have to parse a part of the serial to get the count of CPUs. I will implement this within the next few days. Thank you for pointing this out

**Comment by jherbel** [comment]
If this becomes too complicated, we could also use fmlSysCpuUsage instead. Or does this also depend on the number of cores (i.e., can this go up to for example 300%)?

**Comment by OguzhanCicek** [comment]
i tried asking Fortinet about this but i have not received an answer so far. since the Fortimail system does not directly provide the amount of CPUs it has over snmp i am assuming the check in its current form is correct. You can merge this if you want as it is and i will update it in case my assumption was wrong or you can close this pull request and i will create a new one once i got an answer from Fortinet.

**Comment by jherbel** [comment]
The issue I currently have with this PR are the default levels. Reasonable defaults depend on the number of CPUs. Since this quantity is not available, how about simply removing the default levels? I can do this while merging the PR.

**Comment by OguzhanCicek** [comment]
yes you can remove them. Thank you very much.

**Review by jherbel — APPROVED** [review]

**Pull request closed without merging**
