### PR TITLE
[special_agents] fritzbox bugfixing

### PR DESCRIPTION
**Pull request by 4Syno**
Adjustment for the special agent of the fritzbox :)
Without os version are not recognized in the summary. This is much better

grafik

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, thanks for the PR. The information about the model and the operating system are written to the HW-/SW-Inventory of the host, which is a good place to store them.

**Comment by Yogibaer75** [comment]
Hi Jörg the background was a discussion in the forum why most special agents gave an ugly
Version: unknown, OS: unknown, execution time 0.4 sec
as output of the Check_MK service. This output should be consistent for all types of agent.
For HW/SW information then it would be better to also keep the output lines there and add only the header to the agent output.

**Comment by jherbel** [comment]
Ok I think we can agree on that, lets keep this information in the HW-/SW-Inventory but also add to the output of the Checkmk service

**Comment by jherbel** [comment]
I looked at it more closely and I would say it doesnt make sense to display "OS: AVM FRITZ!....", right? This is the model, not the OS.

**Comment by Yogibaer75** [comment]
Yes you are right best solution would be  --> OS: Fritz!OS  (official name) as a static output of the special agent and Version like it is in the pull request.

**Comment by jherbel** [comment]
We can add OS: Fritz!OS, but the version which the Checkmk service displays is the version of the agent, not the version of the operating system. The special agents are currently unversioned, so we should leave this empty.

**Comment by Yogibaer75** [comment]
From my side it's better than the "unknown" output.
So it is more a internal discussion if the special agents should output a version information or not.
This "problem" will be more and more relevant as more special agents are active in a normal environment.

**Comment by jherbel** [comment]
For now, we will leave the version as it is, since this should stay consistent with the other special agents.

**Pull request closed without merging**
