### PR TITLE
Adding performance data to netapp snapvault check

### PR DESCRIPTION
**Pull request by L4rS6**
Adds performance graphs for netapp api snapvault check.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi Lars,

thanks for your pull request. Before we can look at it more closely, all the tests need to work. You can find more information here:
https://github.com/tribe29/checkmk/blob/master/CONTRIBUTING.md

Best
Jörg

**Comment by jherbel** [comment]
Hello Lars,

thank you for this pull request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-4562

**Comment by L4rS6** [comment]
Hi @jherbel, will this pull request ever be merged? Cheers

**Review by mo-ki — CHANGES_REQUESTED** [review]
Sorry for the long silence -- we are now slowly starting to catch up.
We have since migrated the plugin, so this change is no longer applicable.
However, it is easier to add the metric now: Just add the `metric_name` kwarg to the call of `check_levels` and add an appropriate metric_info. I think `cmk/gui/plugins/metrics/application.py` would the file to put it in. Note that the unit should be seconds, not minutes.

**Comment by mo-ki** [comment]
Hi L4rS6,
I'm closing this due to inactivity. You are welcome to open an updated PR! (refer to my comment above)
Cheers,
 Moritz

**Pull request closed without merging**
